### ISSUE TITLE
Link to preprocessed pairs of GOT-10K and VID dataset 

### ISSUE THREAD

**Issue by balasurajp** [researchmm/SiamDW#1]
Hyperlink is not active or attached.

**Comment by herbert-chen** [comment]
Same problem

**Comment by JudasDie** [comment]
sorry to say that the data is still uploading (~80G). the link will be presented on April 2. @SurajPedasingu  @herbert-chen

**Comment by balasurajp** [comment]
Google Drive link is online but sharing access is not public. Hope you enable it soon.

Thank you!

**Comment by balasurajp** [comment]
Hello, Can you grant me access to download dataset?
