### ISSUE TITLE
can't reproduced the result in paper

### ISSUE THREAD

**Issue by skyshoumeng** [researchmm/SiamDW#101]
Thank you for your great work, but I can't reproduce the result reported in paper，about two percentage lower. I use the code and the models that you provided, and the software environment is the same.  The weird thing is that I can use the raw result you provided trained with GOT-10k (SiamFC) to reproduce the result reported in paper, which should be better than it.  So I am confused, can you tell me where I was wrong? thank you very much.

**Comment by JudasDie** [comment]
> Thank you for your great work, but I can't reproduce the result reported in paper，about two percentage lower. I use the code and the models that you provided, and the software environment is the same. The weird thing is that I can use the raw result you provided trained with GOT-10k (SiamFC) to reproduce the result reported in paper, which should be better than it. So I am confused, can you tell me where I was wrong? thank you very much.

Hi. Please use TPE to tune the hyper-parameters in testing.

**Comment by skyshoumeng** [comment]
Thank you for taking the time to reply.  What I am confused about is whether the hyper-parameters given in the code are the best results from the TPE? 

Look forward to your favourable reply.

Best wishes. 
        Yours respectfully. 
shoumeng Qiu 



发件人: ZP ZHANG
发送时间: 2020年8月20日 16:06
收件人: researchmm/SiamDW
抄送: skyshoumeng; Author
主题: Re: [researchmm/SiamDW] can't reproduced the result in paper (#101)

Thank you for your great work, but I can't reproduce the result reported in paper，about two percentage lower. I use the code and the models that you provided, and the software environment is the same. The weird thing is that I can use the raw result you provided trained with GOT-10k (SiamFC) to reproduce the result reported in paper, which should be better than it. So I am confused, can you tell me where I was wrong? thank you very much.
Hi. Please use TPE to tune the hyper-parameters in testing.

**Comment by JudasDie** [comment]
> Thank you for taking the time to reply. What I am confused about is whether the hyper-parameters given in the code are the best results from the TPE? Look forward to your favourable reply. Best wishes.         Yours respectfully. shoumeng Qiu 发件人: ZP ZHANG 发送时间: 2020年8月20日 16:06 收件人: researchmm/SiamDW 抄送: skyshoumeng; Author 主题: Re: [researchmm/SiamDW] can't reproduced the result in paper (#101) Thank you for your great work, but I can't reproduce the result reported in paper，about two percentage lower. I use the code and the models that you provided, and the software environment is the same. The weird thing is that I can use the raw result you provided trained with GOT-10k (SiamFC) to reproduce the result reported in paper, which should be better than it. So I am confused, can you tell me where I was wrong? thank you very much. Hi. Please use TPE to tune the hyper-parameters in testing. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

The hyper in yaml files is aligned with the model instruction of `test.md`. The models trained on GOT10K is additionally provided, and its hyper for some models and benchmarks is in `readme.md`. If you train on GOT10K by your self, you should tune the hypers with TPE.  If you are not familiar with what these hypers for or why it affects the tracker, I would suggest you to BilibilI to watch my presentation about our new paper Ocean (recently) or SiamDW (one year ago).
