### ISSUE TITLE
请问SiamDW_T的训练方式是否和SiamDW一样

### ISSUE THREAD

**Issue by Alexadlu** [researchmm/SiamDW#104]
在SiamDW_T中只公布的测试代码

**Comment by JudasDie** [comment]
> 在SiamDW_T中只公布的测试代码

你好，不太一样哈，这个算法没有成文所以没有发训练代码。如果需要用我们算法训练可以找我讨论。

**Comment by Alexadlu** [comment]
好的，SiamDW_T训练时是否用了生成的RGBT数据集
