### ISSUE TITLE
vot测试结果

### ISSUE THREAD

**Issue by SilvesterSun** [researchmm/SiamDW#105]
当我在运行python eval_vot.py VOT2016 ./result 2>&1 | tee logs/siamrpn_eval.log的时候，显示：错误: 文件: D:\Tracker_Code\SiamDW_1\lib\core\workspace_load.m 行: 32 列: 18
调用路径上的函数 'varargin' 的语法无效。请使用有效语法或显式初始化 'varargin' 将其转换为变量。
请问一下，这是什么问题呢？谢谢啦。

**Comment by JudasDie** [comment]
> 当我在运行python eval_vot.py VOT2016 ./result 2>&1 | tee logs/siamrpn_eval.log的时候，显示：错误: 文件: D:\Tracker_Code\SiamDW_1\lib\core\workspace_load.m 行: 32 列: 18
> 调用路径上的函数 'varargin' 的语法无效。请使用有效语法或显式初始化 'varargin' 将其转换为变量。
> 请问一下，这是什么问题呢？谢谢啦。

你好，请用新的仓库https://github.com/researchmm/TracKit

**Comment by SilvesterSun** [comment]
非常感谢！
请问能加个微信嘛？我是一个菜鸟，这个代码有一些问题不懂。如果可以的话，我以后有问题可以向您请教吗？我的微信号是s983082671。谢谢啦





------------------ 原始邮件 ------------------
发件人: ZP ZHANG <notifications@github.com&gt;
发送时间: 2020年10月21日 15:55
收件人: researchmm/SiamDW <SiamDW@noreply.github.com&gt;
抄送: SilvesterSun <983082671@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[researchmm/SiamDW] vot测试结果 (#105)





  
当我在运行python eval_vot.py VOT2016 ./result 2&gt;&amp;1 | tee logs/siamrpn_eval.log的时候，显示：错误: 文件: D:\Tracker_Code\SiamDW_1\lib\core\workspace_load.m 行: 32 列: 18
 调用路径上的函数 'varargin' 的语法无效。请使用有效语法或显式初始化 'varargin' 将其转换为变量。
 请问一下，这是什么问题呢？谢谢啦。
  
你好，请用新的仓库https://github.com/researchmm/TracKit

**Comment by JudasDie** [comment]
> 非常感谢！ 请问能加个微信嘛？我是一个菜鸟，这个代码有一些问题不懂。如果可以的话，我以后有问题可以向您请教吗？我的微信号是s983082671。谢谢啦
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: ZP ZHANG <notifications@github.com&gt; 发送时间: 2020年10月21日 15:55 收件人: researchmm/SiamDW <SiamDW@noreply.github.com&gt; 抄送: SilvesterSun <983082671@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[researchmm/SiamDW] vot测试结果 (#105) 当我在运行python eval_vot.py VOT2016 ./result 2&gt;&amp;1 | tee logs/siamrpn_eval.log的时候，显示：错误: 文件: D:\Tracker_Code\SiamDW_1\lib\core\workspace_load.m 行: 32 列: 18 调用路径上的函数 'varargin' 的语法无效。请使用有效语法或显式初始化 'varargin' 将其转换为变量。 请问一下，这是什么问题呢？谢谢啦。 你好，请用新的仓库https://github.com/researchmm/TracKit — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以发我邮箱交流zhangzhipeng2017@ia.ac.cn

**Comment by SilvesterSun** [comment]
好的好的，谢谢。





------------------ 原始邮件 ------------------
发件人: ZP ZHANG <notifications@github.com&gt;
发送时间: 2020年10月21日 16:07
收件人: researchmm/SiamDW <SiamDW@noreply.github.com&gt;
抄送: SilvesterSun <983082671@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[researchmm/SiamDW] vot测试结果 (#105)





  
非常感谢！ 请问能加个微信嘛？我是一个菜鸟，这个代码有一些问题不懂。如果可以的话，我以后有问题可以向您请教吗？我的微信号是s983082671。谢谢啦
 …
 ------------------ 原始邮件 ------------------ 发件人: ZP ZHANG <notifications@github.com&gt; 发送时间: 2020年10月21日 15:55 收件人: researchmm/SiamDW <SiamDW@noreply.github.com&gt; 抄送: SilvesterSun <983082671@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[researchmm/SiamDW] vot测试结果 (#105) 当我在运行python eval_vot.py VOT2016 ./result 2&gt;&amp;1 | tee logs/siamrpn_eval.log的时候，显示：错误: 文件: D:\Tracker_Code\SiamDW_1\lib\core\workspace_load.m 行: 32 列: 18 调用路径上的函数 'varargin' 的语法无效。请使用有效语法或显式初始化 'varargin' 将其转换为变量。 请问一下，这是什么问题呢？谢谢啦。 你好，请用新的仓库https://github.com/researchmm/TracKit — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可以发我邮箱交流zhangzhipeng2017@ia.ac.cn
