### ISSUE TITLE
How to unzip your training pairs?

### ISSUE THREAD

**Issue by loweite** [researchmm/SiamDW#11]
How to unzip your training pairs?

**Comment by JudasDie** [comment]
> How to unzip your training pairs?

If you download from GoogleDrive, you can directly 'unzip' it. The zip files in BaiduDrive is seperated to several smaller zip files since uploading size limit. 
1） for GoogleDrive: unzip xxx.zip
2)  for BaiduDrive:  cat SiamDW_DATA.zip* > SiamDW_DATA.zip && unzip SiamDW_DATA.zip

**Comment by JudasDie** [comment]
This issue will be closed since long-term no reply.
