### ISSUE TITLE
The results of the test model did not meet expectations？

### ISSUE THREAD

**Issue by haizhongli** [researchmm/SiamDW#12]
Thanks for your code fisrt, it help so much. 
According to the configuration process you said, I successfully ran the test code.
I then converted the txt files into a mat files and put it into the OTB framework to calculate the result. However, I found that the SiamFCRes22 model only reached 0.615 on the OTB2013. So I am very confused about what is the reason.

**Comment by JudasDie** [comment]
> Thanks for your code fisrt, it help so much.
> According to the configuration process you said, I successfully ran the test code.
> I then converted the txt files into a mat files and put it into the OTB framework to calculate the result. However, I found that the SiamFCRes22 model only reached 0.615 on the OTB2013. So I am very confused about what is the reason.

1) check your python packages environment again
2) check your translation code
3) the reader in  [closed issuse #2](https://github.com/researchmm/SiamDW/issues/2) has reproduced the result. May there is mistake with some segments during your reproducing.

**Comment by JudasDie** [comment]
> 
> 
> Thanks for your code fisrt, it help so much.
> According to the configuration process you said, I successfully ran the test code.
> I then converted the txt files into a mat files and put it into the OTB framework to calculate the result. However, I found that the SiamFCRes22 model only reached 0.615 on the OTB2013. So I am very confused about what is the reason.

Hello~
Have you fixed the problem? If yes, this issue will be closed.

**Comment by hwpengms** [comment]
Have you fixed the problem？We had test the reproducibility of our training and test code. Also, Lots of other githubers said that they reproduced the results. If you have any problems, pls ping us.

**Comment by hwpengms** [comment]
@haizhongli Have you fixed the problem？We had test the reproducibility of our training and test code. Also, Lots of other githubers said that they reproduced the results. If you have any problems, pls ping us.

**Comment by haizhongli** [comment]
Thank you for your concern. I only saw the code update today, so it's still under testing. If there are any more questions, you may need to be disturbed. Thank you




------------------ 原始邮件 ------------------
发件人: "Houwen Peng"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 晚上7:23
收件人: "researchmm/SiamDW"<SiamDW@noreply.github.com>;
抄送: "﹎╁划濄∑淚"<594387862@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [researchmm/SiamDW] The results of the test model did not meet expectations？ (#12)




@haizhongli Have you fixed the problem？We had test the reproducibility of our training and test code. Also, Lots of other githubers said that they reproduced the results. If you have any problems, pls ping us.

**Comment by haizhongli** [comment]
Thank you for your concern. I only saw the code update today, so it's  still under testing. If there are any more questions, you may need to be  disturbed. Thank you



------------------ 原始邮件 ------------------
发件人: "ZP ZHANG"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 下午5:04
收件人: "researchmm/SiamDW"<SiamDW@noreply.github.com>;
抄送: "﹎╁划濄∑淚"<594387862@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [researchmm/SiamDW] The results of the test model did not meet expectations？ (#12)



 
Thanks for your code fisrt, it help so much.
 According to the configuration process you said, I successfully ran the test code.
 I then converted the txt files into a mat files and put it into the OTB framework to calculate the result. However, I found that the SiamFCRes22 model only reached 0.615 on the OTB2013. So I am very confused about what is the reason.
  
Hello~
 Have you fixed the problem? If yes, this issue will be closed.

**Comment by hwpengms** [comment]
@haizhongli Have you reproduce the results by our code?

**Comment by haizhongli** [comment]
No fine-tuning steps, just train_epoch, I still haven't got a good result. Under 60000 pairs and 50 epoch, the maximum is only 0.6112. 600,000 pairs are only trained 40 times now, and then up to 0.603. I don't know where I disagree and need to be adjusted. Normally, even without fine-tuning, it shouldn't be too bad.



------------------ 原始邮件 ------------------
发件人: "Houwen Peng"<notifications@github.com>;
发送时间: 2019年6月23日(星期天) 中午1:05
收件人: "researchmm/SiamDW"<SiamDW@noreply.github.com>;
抄送: "﹎╁划濄∑淚"<594387862@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [researchmm/SiamDW] The results of the test model did not meet expectations？ (#12)




@haizhongli Have you reproduce the results by our code?

**Comment by haizhongli** [comment]
Dear researcher:      When I looked at the code again, I found that the only trainable parameter for training was the second residual block, features. features. layer2. Did you set it up on purpose? If not, maybe in my environment, there are problems in this place.




------------------ 原始邮件 ------------------
发件人: "Houwen Peng"<notifications@github.com>;
发送时间: 2019年6月23日(星期天) 中午1:05
收件人: "researchmm/SiamDW"<SiamDW@noreply.github.com>;
抄送: "﹎╁划濄∑淚"<594387862@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [researchmm/SiamDW] The results of the test model did not meet expectations？ (#12)




@haizhongli Have you reproduce the results by our code?

**Comment by JudasDie** [comment]
> 
> Dear researcher: When I looked at the code again, I found that the only trainable parameter for training was the second residual block, features. features. layer2. Did you set it up on purpose? If not, maybe in my environment, there are problems in this place.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Houwen Peng"<notifications@github.com>; 发送时间: 2019年6月23日(星期天) 中午1:05 收件人: "researchmm/SiamDW"<SiamDW@noreply.github.com>; 抄送: "﹎╁划濄∑淚"<594387862@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [researchmm/SiamDW] The results of the test model did not meet expectations？ (#12) @haizhongli Have you reproduce the results by our code? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

1) `layer2` means the third stage of resnet.
2) Which training policy do you use now? Unfix all layer at once or gradually? (You can find details in `backbone.py`)
3) Trainable parameter is only layer2 through all 50 epoch or only at the begining of trainig?
4) What's the performance after tuning?

**Comment by haizhongli** [comment]
I haven't noticed the fine-tuning steps before, this will have an impact, the author has been patiently following up on my problem, then I will try para-tune. Any questions, please ask again, thank you

**Comment by haizhongli** [comment]
According to the instructions in readme, the parameters provided by the same environment test author are configured, and the results are consistent with the publication. Thank you for your patient answer.
