### ISSUE TITLE
Questions with mapping labels and images

### ISSUE THREAD

**Issue by BaronH07** [researchmm/SiamDW#15]
Hi Team Researchmm
First, thanks for your brilliant work! 
I encountered problems with the data you provided(both GOT-10k and VID), although the images are cropped to the size 255 times 255, probably the labels still stay the same as that of the original GOT-10k and VID. Can you please explain how to map labels with those cropped images and if it is possible could you please upload the processing file?
Thanks a lot!

**Comment by JudasDie** [comment]
> Hi Team Researchmm
> First, thanks for your brilliant work!
> I encountered problems with the data you provided(both GOT-10k and VID), although the images are cropped to the size 255 times 255, probably the labels still stay the same as that of the original GOT-10k and VID. Can you please explain how to map labels with those cropped images and if it is possible could you please upload the processing file?
> Thanks a lot!
1）In fact you only need to konw the width and height of object, since all objects ar cropped to image center .
2)  The json labels are same as original dataset.
3) As for how to map original object size to that in 255, you can find results in SiamFC dataloader (lib/dataset/siamfc.py)
4) I'll upload a demo layter, however I'm too busy to organize it recently.

**Comment by JudasDie** [comment]
> 
> 
> Hi Team Researchmm
> First, thanks for your brilliant work!
> I encountered problems with the data you provided(both GOT-10k and VID), although the images are cropped to the size 255 times 255, probably the labels still stay the same as that of the original GOT-10k and VID. Can you please explain how to map labels with those cropped images and if it is possible could you please upload the processing file?
> Thanks a lot!

The demo have been uploaded. See [train.md](https://github.com/researchmm/SiamDW/blob/master/lib/tutorials/train.md). This issue will be closed.
