### ISSUE TITLE
Results question

### ISSUE THREAD

**Issue by yuluu** [researchmm/SiamDW#19]
OTB2015 Best: F:\python\tracking\SiamDWmaster\siamese_tracking\result\OTB2015\SiamFCIncep22(0.1734)

The result when i run eval_otb.py .what is the 0.1734?

**Comment by JudasDie** [comment]
> OTB2015 Best: F:\python\tracking\SiamDWmaster\siamese_tracking\result\OTB2015\SiamFCIncep22(0.1734)
> 
> The result when i run eval_otb.py .what is the 0.1734?

Please test model following readme.md. Check each step. Your result seems unresonable. If you have solved your problem, please let me know. If not, show your log to me.

**Comment by yuluu** [comment]
OTB2013 Best: ./result\OTB2013\SiamFCRes22(0.6525)

The result is more correct in OTB2013. So it may be something wrong before.

Thanks for your code.Looking forward to updating.

**Comment by JudasDie** [comment]
> OTB2013 Best: ./result\OTB2013\SiamFCRes22(0.6525)
> 
> The result is more correct in OTB2013. So it may be something wrong before.
> 
> Thanks for your code.Looking forward to updating.

Glad to here that. The issue will be closed. Any other question you can email zhangzhipeng2017@ia.ac.cn.
