### ISSUE TITLE
Was the snapshot model trained by VID？

### ISSUE THREAD

**Issue by herbert-chen** [researchmm/SiamDW#2]
I ran ./snapshot/CIResNet22.pth on OTB2015 and got 0.6437 auc

**Comment by JudasDie** [comment]
> I ran ./snapshot/CIResNet22.pth on OTB2015 and got 0.6437 auc

Please check python version again (including pytorch/opencv/numpy version).

**Comment by JudasDie** [comment]
> I ran ./snapshot/CIResNet22.pth on OTB2015 and got 0.6437 auc

And the provided models for SiamFC are trained on VID.

**Comment by herbert-chen** [comment]
>>> torch.__version__
'0.3.1'
>>> numpy.__version__
'1.12.1'
>>> cv2.__version__
'3.1.0'

According to the results you provided(0.644), it is just about right.
And could you afford some models trained on GOT, thank you~

**Comment by JudasDie** [comment]
> > > > torch.**version**
> > > > '0.3.1'
> > > > numpy.**version**
> > > > '1.12.1'
> > > > cv2.**version**
> > > > '3.1.0'
> 
> According to the results you provided(0.644), it is just about right.
> And could you afford some models trained on GOT, thank you~

I'll provide got10k models later. Thank you for your attention. This question will be closed.
