### ISSUE TITLE
The question for training.

### ISSUE THREAD

**Issue by yuluu** [researchmm/SiamDW#21]
"2>&1 | tee logs/siamfc_train.log" what is it:?  

And when i running the training code. There is a mistake ---"BrokenPipeError: [Errno 32] Broken pipe".

**Comment by JudasDie** [comment]
> "2>&1 | tee logs/siamfc_train.log" what is it:?
> 
> And when i running the training code. There is a mistake ---"BrokenPipeError: [Errno 32] Broken pipe".

1. To generate a log file.
2. I believe these simple questions can be found answers on Baidu or Google. There is no need to open an issue to ask what a shell command means.
3. I never meet Broken pipe errors while training.  It seems something wrong with your CUDA or pytorch.

**Comment by JudasDie** [comment]
> 
> 
> "2>&1 | tee logs/siamfc_train.log" what is it:?
> 
> And when i running the training code. There is a mistake ---"BrokenPipeError: [Errno 32] Broken pipe".

Hello~
Have you fixed your problem? If yes, this issue will be closed.

**Comment by yuluu** [comment]
> > "2>&1 | tee logs/siamfc_train.log" what is it:?
> > And when i running the training code. There is a mistake ---"BrokenPipeError: [Errno 32] Broken pipe".
> 
> Hello~
> Have you fixed your problem? If yes, this issue will be closed.

OK,I will try it again. Thank you

**Comment by yuluu** [comment]
> > > "2>&1 | tee logs/siamfc_train.log" what is it:?
> > > And when i running the training code. There is a mistake ---"BrokenPipeError: [Errno 32] Broken pipe".
> > 
> > 
> > Hello~
> > Have you fixed your problem? If yes, this issue will be closed.
> 
> OK,I will try it again. Thank you

RuntimeError: Error(s) in loading state_dict for SiamRPNRes22:
	size mismatch for connect_model.template_cls.bias: copying a param of torch.Size([5120]) from checkpoint, where the shape is torch.Size([1280]) in current model.
	size mismatch for connect_model.template_cls.weight: copying a param of torch.Size([5120, 512, 3, 3]) from checkpoint, where the shape is torch.Size([1280, 512, 3, 3]) in current model.
	size mismatch for connect_model.template_reg.bias: copying a param of torch.Size([10240]) from checkpoint, where the shape is torch.Size([5120]) in current model.
	size mismatch for connect_model.template_reg.weight: copying a param of torch.Size([10240, 512, 3, 3]) from checkpoint, where the shape is torch.Size([5120, 512, 3, 3]) in current model.
	size mismatch for connect_model.search_cls.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
	size mismatch for connect_model.search_cls.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.
	size mismatch for connect_model.search_reg.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
	size mismatch for connect_model.search_reg.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.

I update the code and the above error occurred when i use SiamRPNRes22 and CIResNet22_RPN.pth to test. It was not appear in the code before.

**Comment by yuluu** [comment]
> > > > "2>&1 | tee logs/siamfc_train.log" what is it:?
> > > > And when i running the training code. There is a mistake ---"BrokenPipeError: [Errno 32] Broken pipe".
> > > 
> > > 
> > > Hello~
> > > Have you fixed your problem? If yes, this issue will be closed.
> > 
> > 
> > OK,I will try it again. Thank you
> 
> RuntimeError: Error(s) in loading state_dict for SiamRPNRes22:
> size mismatch for connect_model.template_cls.bias: copying a param of torch.Size([5120]) from checkpoint, where the shape is torch.Size([1280]) in current model.
> size mismatch for connect_model.template_cls.weight: copying a param of torch.Size([5120, 512, 3, 3]) from checkpoint, where the shape is torch.Size([1280, 512, 3, 3]) in current model.
> size mismatch for connect_model.template_reg.bias: copying a param of torch.Size([10240]) from checkpoint, where the shape is torch.Size([5120]) in current model.
> size mismatch for connect_model.template_reg.weight: copying a param of torch.Size([10240, 512, 3, 3]) from checkpoint, where the shape is torch.Size([5120, 512, 3, 3]) in current model.
> size mismatch for connect_model.search_cls.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
> size mismatch for connect_model.search_cls.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.
> size mismatch for connect_model.search_reg.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
> size mismatch for connect_model.search_reg.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.
> 
> I update the code and the above error occurred when i use SiamRPNRes22 and CIResNet22_RPN.pth to test. It was not appear in the code before.

get_eao.m 
pwd = ['G:\data\tracking\VOT\vot-toolkit-master\', 'vot-workspace', '2016']  % year is a str (can not be a number)  
How to configure here? I am a newer and chicken，so there are more problems. Sorry.

**Comment by JudasDie** [comment]
> > > > > "2>&1 | tee logs/siamfc_train.log" what is it:?
> > > > > And when i running the training code. There is a mistake ---"BrokenPipeError: [Errno 32] Broken pipe".
> > > > 
> > > > 
> > > > Hello~
> > > > Have you fixed your problem? If yes, this issue will be closed.
> > > 
> > > 
> > > OK,I will try it again. Thank you
> > 
> > 
> > RuntimeError: Error(s) in loading state_dict for SiamRPNRes22:
> > size mismatch for connect_model.template_cls.bias: copying a param of torch.Size([5120]) from checkpoint, where the shape is torch.Size([1280]) in current model.
> > size mismatch for connect_model.template_cls.weight: copying a param of torch.Size([5120, 512, 3, 3]) from checkpoint, where the shape is torch.Size([1280, 512, 3, 3]) in current model.
> > size mismatch for connect_model.template_reg.bias: copying a param of torch.Size([10240]) from checkpoint, where the shape is torch.Size([5120]) in current model.
> > size mismatch for connect_model.template_reg.weight: copying a param of torch.Size([10240, 512, 3, 3]) from checkpoint, where the shape is torch.Size([5120, 512, 3, 3]) in current model.
> > size mismatch for connect_model.search_cls.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
> > size mismatch for connect_model.search_cls.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.
> > size mismatch for connect_model.search_reg.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
> > size mismatch for connect_model.search_reg.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.
> > I update the code and the above error occurred when i use SiamRPNRes22 and CIResNet22_RPN.pth to test. It was not appear in the code before.
> 
> get_eao.m
> pwd = ['G:\data\tracking\VOT\vot-toolkit-master', 'vot-workspace', '2016'] % year is a str (can not be a number)
> How to configure here? I am a newer and chicken，so there are more problems. Sorry.

1) The first problem has been fixed. An additional key word `cls_type` is needed. See test.md
2) You should set up vot-toolkit according to official [tutorial](https://www.baidu.com/link?url=l27Jc72CtOQAwrlQKgmh-2bHjKrB8X494k1jrYy7H4trG7_oXnQ--d67VhjfhVUz&wd=&eqid=e5649eb5002d5ae7000000035d0dcf0a)
3) It's suggested that you should read some papers to get familiar with common tracking benchmarks.
4) Any proplem not related to this code please email me (zhangzhipeng2017@ia.ac.cn). I can give you more guildence through email  than git-issue. 
5) If you have fixed this problem, please close this issue.

**Comment by yuluu** [comment]
> > > > > > "2>&1 | tee logs/siamfc_train.log" what is it:?
> > > > > > And when i running the training code. There is a mistake ---"BrokenPipeError: [Errno 32] Broken pipe".
> > > > > 
> > > > > 
> > > > > Hello~
> > > > > Have you fixed your problem? If yes, this issue will be closed.
> > > > 
> > > > 
> > > > OK,I will try it again. Thank you
> > > 
> > > 
> > > RuntimeError: Error(s) in loading state_dict for SiamRPNRes22:
> > > size mismatch for connect_model.template_cls.bias: copying a param of torch.Size([5120]) from checkpoint, where the shape is torch.Size([1280]) in current model.
> > > size mismatch for connect_model.template_cls.weight: copying a param of torch.Size([5120, 512, 3, 3]) from checkpoint, where the shape is torch.Size([1280, 512, 3, 3]) in current model.
> > > size mismatch for connect_model.template_reg.bias: copying a param of torch.Size([10240]) from checkpoint, where the shape is torch.Size([5120]) in current model.
> > > size mismatch for connect_model.template_reg.weight: copying a param of torch.Size([10240, 512, 3, 3]) from checkpoint, where the shape is torch.Size([5120, 512, 3, 3]) in current model.
> > > size mismatch for connect_model.search_cls.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
> > > size mismatch for connect_model.search_cls.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.
> > > size mismatch for connect_model.search_reg.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
> > > size mismatch for connect_model.search_reg.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.
> > > I update the code and the above error occurred when i use SiamRPNRes22 and CIResNet22_RPN.pth to test. It was not appear in the code before.
> > 
> > 
> > get_eao.m
> > pwd = ['G:\data\tracking\VOT\vot-toolkit-master', 'vot-workspace', '2016'] % year is a str (can not be a number)
> > How to configure here? I am a newer and chicken，so there are more problems. Sorry.
> 
> 1. The first problem has been fixed. An additional key word `cls_type` is needed. See test.md
> 2. You should set up vot-toolkit according to official [tutorial](https://www.baidu.com/link?url=l27Jc72CtOQAwrlQKgmh-2bHjKrB8X494k1jrYy7H4trG7_oXnQ--d67VhjfhVUz&wd=&eqid=e5649eb5002d5ae7000000035d0dcf0a)
> 3. It's suggested that you should read some papers to get familiar with common tracking benchmarks.
> 4. Any proplem not related to this code please email me ([zhangzhipeng2017@ia.ac.cn](mailto:zhangzhipeng2017@ia.ac.cn)). I can give you more guildence through email  than git-issue.
> 5. If you have fixed this problem, please close this issue.

The first  problem  occurred when i ran the  run_video.py. I will close this issue after I solved this problem.Thank you very much。

**Comment by yuluu** [comment]
> > > > > > > "2>&1 | tee logs/siamfc_train.log" what is it:?
> > > > > > > And when i running the training code. There is a mistake ---"BrokenPipeError: [Errno 32] Broken pipe".
> > > > > > 
> > > > > > 
> > > > > > Hello~
> > > > > > Have you fixed your problem? If yes, this issue will be closed.
> > > > > 
> > > > > 
> > > > > OK,I will try it again. Thank you
> > > > 
> > > > 
> > > > RuntimeError: Error(s) in loading state_dict for SiamRPNRes22:
> > > > size mismatch for connect_model.template_cls.bias: copying a param of torch.Size([5120]) from checkpoint, where the shape is torch.Size([1280]) in current model.
> > > > size mismatch for connect_model.template_cls.weight: copying a param of torch.Size([5120, 512, 3, 3]) from checkpoint, where the shape is torch.Size([1280, 512, 3, 3]) in current model.
> > > > size mismatch for connect_model.template_reg.bias: copying a param of torch.Size([10240]) from checkpoint, where the shape is torch.Size([5120]) in current model.
> > > > size mismatch for connect_model.template_reg.weight: copying a param of torch.Size([10240, 512, 3, 3]) from checkpoint, where the shape is torch.Size([5120, 512, 3, 3]) in current model.
> > > > size mismatch for connect_model.search_cls.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
> > > > size mismatch for connect_model.search_cls.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.
> > > > size mismatch for connect_model.search_reg.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([256]) in current model.
> > > > size mismatch for connect_model.search_reg.weight: copying a param of torch.Size([512, 512, 3, 3]) from checkpoint, where the shape is torch.Size([256, 512, 3, 3]) in current model.
> > > > I update the code and the above error occurred when i use SiamRPNRes22 and CIResNet22_RPN.pth to test. It was not appear in the code before.
> > > 
> > > 
> > > get_eao.m
> > > pwd = ['G:\data\tracking\VOT\vot-toolkit-master', 'vot-workspace', '2016'] % year is a str (can not be a number)
> > > How to configure here? I am a newer and chicken，so there are more problems. Sorry.
> > 
> > 
> > 
> > 1. The first problem has been fixed. An additional key word `cls_type` is needed. See test.md
> > 2. You should set up vot-toolkit according to official [tutorial](https://www.baidu.com/link?url=l27Jc72CtOQAwrlQKgmh-2bHjKrB8X494k1jrYy7H4trG7_oXnQ--d67VhjfhVUz&wd=&eqid=e5649eb5002d5ae7000000035d0dcf0a)
> > 3. It's suggested that you should read some papers to get familiar with common tracking benchmarks.
> > 4. Any proplem not related to this code please email me ([zhangzhipeng2017@ia.ac.cn](mailto:zhangzhipeng2017@ia.ac.cn)). I can give you more guildence through email  than git-issue.
> > 5. If you have fixed this problem, please close this issue.
> 
> The first problem occurred when i ran the run_video.py. I will close this issue after I solved this problem.Thank you very much。

I have solved this problem.
