### ISSUE TITLE
The scale of response map.

### ISSUE THREAD

**Issue by iminfine** [researchmm/SiamDW#23]
Thanks for your great work! It helps me a lot.  

The code of convolution layer of Siamfc model is:
`def forward(self, z_f, x_f):
        if not self.training:
            return 0.1 * F.conv2d(x_f, z_f)
        else:
            return 0.1 * self._conv2d_group(x_f, z_f)`

Why change the scale of the results of cross-correlation?  How to determine parameter 0.1?

**Comment by JudasDie** [comment]
> Thanks for your great work! It helps me a lot.
> 
> The code of convolution layer of Siamfc model is:
> `def forward(self, z_f, x_f): if not self.training: return 0.1 * F.conv2d(x_f, z_f) else: return 0.1 * self._conv2d_group(x_f, z_f)`
> 
> Why change the scale of the results of cross-correlation? How to determine parameter 0.1?

You can use the weight learned from network(a 1*1 conv layer) or simply give a scale factor. There is no obvious difference on performance.  Any other question?

**Comment by iminfine** [comment]
> > Thanks for your great work! It helps me a lot.
> > The code of convolution layer of Siamfc model is:
> > `def forward(self, z_f, x_f): if not self.training: return 0.1 * F.conv2d(x_f, z_f) else: return 0.1 * self._conv2d_group(x_f, z_f)`
> > Why change the scale of the results of cross-correlation? How to determine parameter 0.1?
> 
> You can use the weight learned from network(a 1*1 conv layer) or simply give a scale factor. There is no obvious difference on performance. Any other question?

Sorry, I still don't understand. If there is no difference of them, why do that? How about use the results of  cross-correlation directly like this:  
`def forward(self, z_f, x_f): if not self.training: return F.conv2d(x_f, z_f) else: return * self._conv2d_group(x_f, z_f)` ?

**Comment by JudasDie** [comment]
> 
> 
> > > Thanks for your great work! It helps me a lot.
> > > The code of convolution layer of Siamfc model is:
> > > `def forward(self, z_f, x_f): if not self.training: return 0.1 * F.conv2d(x_f, z_f) else: return 0.1 * self._conv2d_group(x_f, z_f)`
> > > Why change the scale of the results of cross-correlation? How to determine parameter 0.1?
> > 
> > 
> > You can use the weight learned from network(a 1*1 conv layer) or simply give a scale factor. There is no obvious difference on performance. Any other question?
> 
> Sorry, I still don't understand. If there is no difference of them, why do that? How about use the results of cross-correlation directly like this:
> `def forward(self, z_f, x_f): if not self.training: return F.conv2d(x_f, z_f) else: return * self._conv2d_group(x_f, z_f)` ?

We usually use a 1*1 conv layer to adjust the scale of correlation output. The output of correlation is usually very large at the beginning of training phase, a small scale factor is beneficial to network convergence.

**Comment by iminfine** [comment]
> > > > Thanks for your great work! It helps me a lot.
> > > > The code of convolution layer of Siamfc model is:
> > > > `def forward(self, z_f, x_f): if not self.training: return 0.1 * F.conv2d(x_f, z_f) else: return 0.1 * self._conv2d_group(x_f, z_f)`
> > > > Why change the scale of the results of cross-correlation? How to determine parameter 0.1?
> > > 
> > > 
> > > You can use the weight learned from network(a 1*1 conv layer) or simply give a scale factor. There is no obvious difference on performance. Any other question?
> > 
> > 
> > Sorry, I still don't understand. If there is no difference of them, why do that? How about use the results of cross-correlation directly like this:
> > `def forward(self, z_f, x_f): if not self.training: return F.conv2d(x_f, z_f) else: return * self._conv2d_group(x_f, z_f)` ?
> 
> We usually use a 1*1 conv layer to adjust the scale of correlation output. The output of correlation is usually very large at the beginning of training phase, a small scale factor is beneficial to network convergence.

Thanks.
