### ISSUE TITLE
The principal of selecting parameters.

### ISSUE THREAD

**Issue by iminfine** [researchmm/SiamDW#25]
I notice that different parameters are used when test proposed models with different benchmarks.
For example, the parameters of SiamFCRes22 of OTB2015 are 
`scale_step: 1.1897 
 scale_lr: 0.2226
 scale_penalty: 0.9370
 w_influence: 0.2897`
Could you please detail the selection strategy?

**Comment by JudasDie** [comment]
> 
> 
> I notice that different parameters are used when test proposed models with different benchmarks.
> For example, the parameters of SiamFCRes22 of OTB2015 are
> `scale_step: 1.1897 scale_lr: 0.2226 scale_penalty: 0.9370 w_influence: 0.2897`
> Could you please detail the selection strategy?

See `tune_tpe.py` for details.

**Comment by iminfine** [comment]
> > I notice that different parameters are used when test proposed models with different benchmarks.
> > For example, the parameters of SiamFCRes22 of OTB2015 are
> > `scale_step: 1.1897 scale_lr: 0.2226 scale_penalty: 0.9370 w_influence: 0.2897`
> > Could you please detail the selection strategy?
> 
> See `tune_tpe.py` for details.

Thank you for your prompt reply!
