### ISSUE TITLE
About get_eao.m

### ISSUE THREAD

**Issue by Re3write** [researchmm/SiamDW#28]
what can i modify the pwd in the get_eao.m to make the evaluation work? i am a stranger to VOT dataset. And should i need to run the workspace_create.m in the toolkit?

**Comment by JudasDie** [comment]
> 
> 
> what can i modify the pwd in the get_eao.m to make the evaluation work? i am a stranger to VOT dataset. And should i need to run the workspace_create.m in the toolkit?

Yes, the function can be used after you setting up VOT workspace. Refer to [official tutorial](http://www.votchallenge.net/howto/integration_channels.html) pls.

**Comment by Re3write** [comment]
Thanks a lot

**Comment by Re3write** [comment]
I got 0.354 on vot2016 using the  CIResNet22_RPN.pth from google driver，Is the same chekpoint in the paper which score is 0.370?

**Comment by JudasDie** [comment]
> I got 0.354 on vot2016 using the CIResNet22_RPN.pth from google driver，Is the same chekpoint in the paper which score is 0.370?

The model is aligned with `readme.md` results. Check your python packages version, and pls keep consistent with `install_rpn.sh`. And then check hyper-parameters in `experiment/test/xx.taml` .

**Comment by Re3write** [comment]
There is only CIResNext22-RPN result in readme, but i use the CIResNet22_RPN from google driver. I follow the hyper-parameters in experiment/test/SiamRPNRes22.yaml. Thanks

**Comment by JudasDie** [comment]
> There is only CIResNext22-RPN result in readme, but i use the CIResNet22_RPN from google driver. I follow the hyper-parameters in experiment/test/SiamRPNRes22.yaml. Thanks

Yes, the model is for CIResNext22-RPN. I'll fix spell error in `readme`.

**Comment by Re3write** [comment]
ok, i will check my code. Thanks~
