### ISSUE TITLE
Pretrained model preparation

### ISSUE THREAD

**Issue by junliang230** [researchmm/SiamDW#29]
There seems to be a problem with BaiduDrive links of Pretrained model preparation? could you fix it, thanks!

**Comment by JudasDie** [comment]
> 
> 
> There seems to be a problem with BaiduDrive links of Pretrained model preparation? could you fix it, thanks!

The problem has been fixed. I found BaiduDrive link may become invalid after seven days, so pls try GoogleDrive and OneDrive first.

**Comment by junliang230** [comment]
thanks a lot

**Comment by JudasDie** [comment]
> 
> 
> thanks a lot

You'r welcome and the issue will be closed.
