### ISSUE TITLE
Submission to vot-challenge

### ISSUE THREAD

**Issue by balasurajp** [researchmm/SiamDW#3]
How are you planning to submit your results to vot-challenge?

Is it the same way you are doing it now by copying handcrafted script results to vot-workspace?

because vot-toolkit works only with pytorch=0.3.1

any related suggestion would be helpful :) 
Thank you

**Comment by JudasDie** [comment]
1) I wrote these scripts for fast testing/tuning. VOT-TOOLKIT with matlab is slow in common sense.
2) You can modify our testing script into vot-toolkit, it's easy i think.
3) Our SiamFC is tested on pytorch 0.3.1. Although siamrpn is tested on pytorch 0.4.1, pytorch 0.3.1 can give same results.  Be careful of other package version like opencv/numpy.
4) In a real competition (VOT2019 is coming), you can use our script for fast testing and tuning. After optimal hyper-parameters being fixed, make a vot-toolkit style code.

Is my answer helpful? @SurajPedasingu

**Comment by JudasDie** [comment]
This issue will be closed since long-term no reply.
