### ISSUE TITLE
Tune_gene

### ISSUE THREAD

**Issue by iminfine** [researchmm/SiamDW#30]

**Comment by iminfine** [comment]
I rerun TPE many times and succeed finally, it is too slow. I then return to use GA with multi-GPUs by the following command:  
`mpiexec -n 8 python -u ./siamese_tracking/tune_gene.py`
I notice that the speed of each thread(about 1 hour with OTB2013) is much slower than running GA with a single thread(20minutes).
Do you face the same problem when you test it? Any suggestions？

**Comment by JudasDie** [comment]
> 
> 
> I rerun TPE many times and succeed finally, it is too slow. I then return to use GA with multi-GPUs by the following command:
> `mpiexec -n 8 python -u ./siamese_tracking/tune_gene.py`
> I notice that the speed of each thread(about 1 hour with OTB2013) is much slower than running GA with a single thread(20minutes).
> Do you face the same problem when you test it? Any suggestions？

I didn't meet that problem. I realized that you have opened several questions about tuning process. Email me for details may be better.

**Comment by iminfine** [comment]
> > I rerun TPE many times and succeed finally, it is too slow. I then return to use GA with multi-GPUs by the following command:
> > `mpiexec -n 8 python -u ./siamese_tracking/tune_gene.py`
> > I notice that the speed of each thread(about 1 hour with OTB2013) is much slower than running GA with a single thread(20minutes).
> > Do you face the same problem when you test it? Any suggestions？
> 
> I didn't meet that problem. I realized that you have opened several questions about tuning process. Email me for details may be better.

Thanks, I will send email to you if I have other questions about tuning.
