### ISSUE TITLE
How to train a model on myself dataset? How to organize the dataset to a json file?

### ISSUE THREAD

**Issue by mryoungci** [researchmm/SiamDW#32]
When i try to train a model on my dataset , i find the SiamFC.yaml Annotation infomation is organized to a json file.  But,  i can not find a json file sample in the code.
How should i organize the dataset to a json file?  Can you upload this json file sample and explain it?  3Q so much,

**Comment by JudasDie** [comment]
> When i try to train a model on my dataset , i find the SiamFC.yaml Annotation infomation is organized to a json file. But, i can not find a json file sample in the code.
> How should i organize the dataset to a json file? Can you upload this json file sample and explain it? 3Q so much,

I've uploaded a json generation script. You can find it in `train.md/Data optimization`. Any other question?

**Comment by mryoungci** [comment]
Thank you for your answer. I will try it.
I'll come back to ask you for help later if I have any questions about the task

**Comment by jwma0725** [comment]
> > When i try to train a model on my dataset , i find the SiamFC.yaml Annotation infomation is organized to a json file. But, i can not find a json file sample in the code.
> > How should i organize the dataset to a json file? Can you upload this json file sample and explain it? 3Q so much,
> 
> I've uploaded a json generation script. You can find it in `train.md/Data optimization`. Any other question?

Hi, I have the same problem, and  I can't download these files, could you send these files to my email? thanks.

**Comment by Totoro-wen** [comment]
Hello, I have the same problem, I can't download these files, can you send a link again?
VID, YouTubebb, DET, COCO, LASOT json file where can be found.
Thanks a lot.

**Comment by mryoungci** [comment]
> Hello, I have the same problem, I can't download these files, can you send a link again?
> VID, YouTubebb, DET, COCO, LASOT json file where can be found.
> Thanks a lot.

https://github.com/researchmm/SiamDW/blob/master/lib/tutorials/train.md
https://pan.baidu.com/s/17_qGxspaXC96SzyPwP5rmQ
BaiduDrive extracted code:bnd9

**Comment by jwma0725** [comment]
Hi， I don't have these json files, but I can share these downloaded files.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mryoungci"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 下午5:37
收件人:&nbsp;"researchmm/SiamDW"<SiamDW@noreply.github.com&gt;;
抄送:&nbsp;"M保罗"<1296816492@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [researchmm/SiamDW] How to train a model on myself dataset? How to organize the dataset to a json file? (#32)



 
Hello, I have the same problem, I can't download these files, can you send a link again?
 VID, YouTubebb, DET, COCO, LASOT json file where can be found.
 Thanks a lot.
  
https://github.com/researchmm/SiamDW/blob/master/lib/tutorials/train.md
 https://pan.baidu.com/s/17_qGxspaXC96SzyPwP5rmQ
 BaiduDrive extracted code:bnd9

**Comment by Totoro-wen** [comment]
> Hi， I don't have these json files, but I can share these downloaded files.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"mryoungci"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月1日(星期五) 下午5:37 收件人:&nbsp;"researchmm/SiamDW"<SiamDW@noreply.github.com&gt;; 抄送:&nbsp;"M保罗"<1296816492@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [researchmm/SiamDW] How to train a model on myself dataset? How to organize the dataset to a json file? (#32) Hello, I have the same problem, I can't download these files, can you send a link again? VID, YouTubebb, DET, COCO, LASOT json file where can be found. Thanks a lot. https://github.com/researchmm/SiamDW/blob/master/lib/tutorials/train.md https://pan.baidu.com/s/17_qGxspaXC96SzyPwP5rmQ BaiduDrive extracted code:bnd9 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Please share me the json file.Thanks.

**Comment by mryoungci** [comment]
the json file is  generated by python script writed by the author.
you can download from the following ulr:
https://drive.google.com/file/d/1xytp3_vcaFC9Hvlqvei1PL8P5MhI7f0Y/view?usp=sharing
 
see train.md/Data optimization for details

**Comment by mryoungci** [comment]
> Hello, I have the same problem, I can't download these files, can you send a link again?
> VID, YouTubebb, DET, COCO, LASOT json file where can be found.
> Thanks a lot.

the json file is generated by python script writed by the author.
you can download from the following ulr:
https://drive.google.com/file/d/1xytp3_vcaFC9Hvlqvei1PL8P5MhI7f0Y/view?usp=sharing

see train.md/Data optimization for details
https://github.com/researchmm/SiamDW/blob/master/lib/tutorials/train.md
"We provide a demo to generate training pairs. You can modify it to process any data you want."

**Comment by jwma0725** [comment]
Sorry, I don't have these json files.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mryoungci"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 下午5:29
收件人:&nbsp;"researchmm/SiamDW"<SiamDW@noreply.github.com&gt;;
抄送:&nbsp;"M保罗"<1296816492@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [researchmm/SiamDW] How to train a model on myself dataset? How to organize the dataset to a json file? (#32)



 
Hello, I have the same problem, I can't download these files, can you send a link again?
 VID, YouTubebb, DET, COCO, LASOT json file where can be found.
 Thanks a lot.
  
the json file is generated by python script writed by the author.
 you can download from the following ulr:
 https://drive.google.com/file/d/1xytp3_vcaFC9Hvlqvei1PL8P5MhI7f0Y/view?usp=sharing
 
see train.md/Data optimization for details
 https://github.com/researchmm/SiamDW/blob/master/lib/tutorials/train.md
 "We provide a demo to generate training pairs. You can modify it to process any data you want."
