### ISSUE TITLE
Are there other pretrained models?

### ISSUE THREAD

**Issue by gh18l** [researchmm/SiamDW#33]
Is there any pretrained model for deeper model than XX22 such as ResNet50 with SiamFC?

**Comment by JudasDie** [comment]
> Is there any pretrained model for deeper model than XX22 such as ResNet50 with SiamFC?
 
Hi~ Does CIR43 （stride 4） meet your needs？If it's useful to you, I can send to your email. Is there anything I can help you?

**Comment by gh18l** [comment]
@JudasDie My email is liguangh1996@gmail.com, thank you for your generosity!

**Comment by JudasDie** [comment]
> @JudasDie My email is [liguangh1996@gmail.com](mailto:liguangh1996@gmail.com), thank you for your generosity!

You're welcome. And thanks for your interest on our work. I'll send to you later.
