### ISSUE TITLE
LaSOT only contains the results for 279 videos

### ISSUE THREAD

**Issue by HengLan** [researchmm/SiamDW#34]
Hi, Zhipeng,

A nice work! I noticed that for LaSOT, you only provide the results for 279 videos. Did you want us to guess which one was missing (I am kidding :))? Could you please share the complete version. Thanks.

**Comment by JudasDie** [comment]
> Hi, Zhipeng,
> 
> A nice work! I noticed that for LaSOT, you only provide the results for 279 videos. Did you want us to guess which one was missing (I am kidding :))? Could you please share the complete version. Thanks.

Oh~ my mistake. Thanks for your notice. I'll update it later.  The testing json file that I download from another tracking repo contains 279 videos.  I'll check which video is missing and re-tune it. It may take some time. Do you need the testing hyper-parameters now?

**Comment by HengLan** [comment]
Thanks for the reply. That is fine. It’s not urgent. Take your time!


ZP ZHANG <notifications@github.com>于2019年8月15日 周四上午10:49写道：

**Comment by hwpengms** [comment]
> Thanks for the reply. That is fine. It’s not urgent. Take your time!
> 
> 
> ZP ZHANG <notifications@github.com>于2019年8月15日 周四上午10:49写道：
> …

@HengLan Thanks Heng for your kind notice :)
