### ISSUE TITLE
About Toolkit preparation in SiamRPN training

### ISSUE THREAD

**Issue by kasuo511** [researchmm/SiamDW#36]
Thanks for sharing your code first. I am sorry to bother you as a deep learning beginner.
I did modified path_to/toolkit in lib/core/get_eao.m to my vot-toolkit path as

```
addpath('/home/ltp/vot-toolkit/'); toolkit_path; % Make sure that VOT toolkit is in the path
pwd = ['/home/ltp/vot-toolkit/', 'vot', year]  % year is a str (can not be a number)
```

but I still got warning before training like this:

```
File /home/ltp/桌面/Workspace/SiamDW-master/lib/core/get_eao.m, line 12, in get_eao
unrecognized argument /home/ltp/vot-toolkit/vot2017
```

This problem has bothered me for weeks，hope you can help，thanks.

![20190830151133](https://user-images.githubusercontent.com/19659016/64000519-84e94d00-cb38-11e9-9315-90656eb85d94.png)

**Comment by JudasDie** [comment]
> Thanks for sharing your code first. I am sorry to bother you as a deep learning beginner.
> I did modified path_to/toolkit in lib/core/get_eao.m to my vot-toolkit path as
> 
> ```
> addpath('/home/ltp/vot-toolkit/'); toolkit_path; % Make sure that VOT toolkit is in the path
> pwd = ['/home/ltp/vot-toolkit/', 'vot', year]  % year is a str (can not be a number)
> ```
> 
> but I still got warning before training like this:
> 
> ```
> File /home/ltp/桌面/Workspace/SiamDW-master/lib/core/get_eao.m, line 12, in get_eao
> unrecognized argument /home/ltp/vot-toolkit/vot2017
> ```
> 
> This problem has bothered me for weeks，hope you can help，thanks.
> 
> ![20190830151133](https://user-images.githubusercontent.com/19659016/64000519-84e94d00-cb38-11e9-9315-90656eb85d94.png)

Thanks for your interest. Have you set up VOT workspace before testing?
I think I found where the problem is. The original `workspace_load.m`  does't take any input arguments. You can modify `workspace_load.m` to receive an input argument.

**Comment by kasuo511** [comment]
It is exactly where my problem lies. That helps a lot.
I modified my `workspace_load.m` file, line 33 to:

`case '/home/ltp/vot-toolkit/vot2017', directory = args{j+1};`

and now the code is downloading for something I have no idea.
![20190830162846](https://user-images.githubusercontent.com/19659016/64005745-92f09b00-cb43-11e9-836a-d13c30b8cf34.png)

**Comment by JudasDie** [comment]
> It is exactly where my problem lies. That helps a lot.
> I modified my `workspace_load.m` file, line 33 to:
> 
> `case '/home/ltp/vot-toolkit/vot2017', directory = args{j+1};`
> 
> and now the code is downloading for something I have no idea.
> ![20190830162846](https://user-images.githubusercontent.com/19659016/64005745-92f09b00-cb43-11e9-836a-d13c30b8cf34.png)

Please see 'siamese_tracking/train_xx.py'. The code will download pretrained model from GoogleDrive  automatically.

**Comment by kasuo511** [comment]
> > It is exactly where my problem lies. That helps a lot.
> > I modified my `workspace_load.m` file, line 33 to:
> > `case '/home/ltp/vot-toolkit/vot2017', directory = args{j+1};`
> > and now the code is downloading for something I have no idea.
> > ![20190830162846](https://user-images.githubusercontent.com/19659016/64005745-92f09b00-cb43-11e9-836a-d13c30b8cf34.png)
> 
> Please see 'siamese_tracking/train_xx.py'. The code will download pretrained model from GoogleDrive automatically.

Thank you for all your help! I'll find a vpn and download the GOT10K pretrained model, you may close the issue. Have a nice weekend.

**Comment by JudasDie** [comment]
> > 
> 
> Thank you for all your help! I'll find a vpn and download the GOT10K pretrained m

Glad that I can help you. You can email me (zhangzhipeng2017@ia.ac.cn) if you have any other questions. :)
