### ISSUE TITLE
Some errors occured when unzipped SiamDW_DATA in Baidu driver

### ISSUE THREAD

**Issue by ShiLongCheng** [researchmm/SiamDW#37]
Thank you for your excellent job in object tracking area. I downloaded the SiamDW_DATA datas in Baidu driver,but some errors occured when I tried to unzip the datasets.The errors are shown below.
![image](https://user-images.githubusercontent.com/38320388/64071433-e03c4c00-ccac-11e9-9423-77befbe1530b.png)
I tried several times,but there are same problems, **I don't know how to solve these problem.Could you help me? or someone could help me?**

**Comment by JudasDie** [comment]
> Thank you for your excellent job in object tracking area. I downloaded the SiamDW_DATA datas in Baidu driver,but some errors occured when I tried to unzip the datasets.The errors are shown below.
> ![image](https://user-images.githubusercontent.com/38320388/64071433-e03c4c00-ccac-11e9-9423-77befbe1530b.png)
> I tried several times,but there are same problems, **I don't know how to solve these problem.Could you help me? or someone could help me?**

Hi~. Please refers to [issue11](https://github.com/researchmm/SiamDW/issues/11). BTW, you should unzip them on Linux system. Hope this can help you.

**Comment by ShiLongCheng** [comment]
Thank you for your reply,I'll try it.

**Comment by JudasDie** [comment]
> Thank you for your reply,I'll try it.

Glad to help you.
