### ISSUE TITLE
NaN or Inf found in input tensor

### ISSUE THREAD

**Issue by QIQIVTrackingY** [researchmm/SiamDW#38]
I get the problem 'NaN or Inf found in input tensor' when training SiamRPN in the dataset that you give.

**Comment by JudasDie** [comment]
> I get the problem 'NaN or Inf found in input tensor' when training SiamRPN in the dataset that you give.

Hi~ Thanks your interest on our work. I didn't meet your problem. Could you debug the label of data? It seems error happens with log function.

**Comment by QIQIVTrackingY** [comment]
Thank you! I get RuntimeWarning: invaild value encountered in log
delta[2]=np.log(tw/(w+eps)+eps)
delta[3]=np.log(th/(h+eps)+eps)

**Comment by JudasDie** [comment]
> Thank you! I get RuntimeWarning: invaild value encountered in log
> delta[2]=np.log(tw/(w+eps)+eps)
> delta[3]=np.log(th/(h+eps)+eps)

Glad that I can help you. If you have other questions, pls email me zhangzhipeng2017@ia.ac.cn.

**Comment by btoob** [comment]
> Thank you! I get RuntimeWarning: invaild value encountered in log
> delta[2]=np.log(tw/(w+eps)+eps)
> delta[3]=np.log(th/(h+eps)+eps)





> I get the problem 'NaN or Inf found in input tensor' when training SiamRPN in the dataset that you give.

hi~I meet the same problem~could u help me for how to modify these two equations～thank u so much～

**Comment by btoob** [comment]
> Thank you! I get RuntimeWarning: invaild value encountered in log
> delta[2]=np.log(tw/(w+eps)+eps)
> delta[3]=np.log(th/(h+eps)+eps)

hi .I meet the same problem. could u help me for how to modify these two equations～thank u so much～

**Comment by ISosnovik** [comment]
This error still occurs. How to fix it?
