### ISSUE TITLE
Can not download parameter tuning toolkit  

### ISSUE THREAD

**Issue by QIQIVTrackingY** [researchmm/SiamDW#39]
Hello,the link of parameter tuning toolkit  is not available for me.

**Comment by JudasDie** [comment]
> Hello,the link of parameter tuning toolkit is not available for me.

Hi~ Thanks for your interest. The tuning toolkit  is embedded in codes, you do not need to download again. Check `siamese_tracking/tune_tps.py` pls.

**Comment by QIQIVTrackingY** [comment]
Thank&nbsp; you!



---Original---

**Comment by JudasDie** [comment]
> Thank&nbsp; you!
> […](#)
> ---Original--- From: "ZP ZHANG"<notifications@github.com&gt; Date: Thu, Sep 12, 2019 09:50 AM To: "researchmm/SiamDW"<SiamDW@noreply.github.com&gt;; Cc: "Author"<author@noreply.github.com&gt;;"QIQIVTrackingY"<645372015@qq.com&gt;; Subject: Re: [researchmm/SiamDW] Can not download parameter tuning toolkit (#39) Hello,the link of parameter tuning toolkit is not available for me. Hi~ Thanks for your interest. The tuning toolkit is embedded in codes, you do not need to download again. Check siamese_tracking/tune_tps.py pls. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

You are so welcom. And if you need other help, please email me (zhipengzhang2017@ia.ac.cn)
