### ISSUE TITLE
Is the preprocess method of GOT-10K and VID the same as SiamFC paper?

### ISSUE THREAD

**Issue by herbert-chen** [researchmm/SiamDW#4]
Thanks for your code fisrt, it help so much
Here is a question:
I used the same processing method  as  SiamFC paper mentioned to preprocess the GOT-10K, but when I tried to train SiamFCRes22 on it, the auc result of OTB2015 is only 0.61+

**Comment by JudasDie** [comment]
> Thanks for your code fisrt, it help so much
> Here is a question:
> I used the same processing method as SiamFC paper mentioned to preprocess the GOT-10K, but when I tried to train SiamFCRes22 on it, the auc result of OTB2015 is only 0.61+

1） have you tuning hyper-parameter?
2)    the default settings in `SiamFC.yaml`  can give a pretty good results, especially when GOT10K is used.

**Comment by wangaixue** [comment]
@herbert-chen did you use the author pre-process  VID and got-10k??

**Comment by herbert-chen** [comment]
No, that google drive file is too large
@wangaixue

**Comment by wangaixue** [comment]
can you share me your link? the link the author provided has  the root  @herbert-chen

**Comment by JudasDie** [comment]
> can you share me your link? the link the author provided has  the root  @herbert-chen

you can apply to access, and will be permitted sooner.

**Comment by JudasDie** [comment]
> No, that google drive file is too large
> @wangaixue

the pairs are same as original SiamFC.

**Comment by JudasDie** [comment]
> 
> 
> Thanks for your code fisrt, it help so much
> Here is a question:
> I used the same processing method as SiamFC paper mentioned to preprocess the GOT-10K, but when I tried to train SiamFCRes22 on it, the auc result of OTB2015 is only 0.61+

We provide more training data now, including VID, YTB, COCO, DET, GOT10K and LASOT. And a pre-processing script is available. See [train.md](https://github.com/researchmm/SiamDW/blob/master/lib/tutorials/train.md) for details. This issue will be closed.
