### ISSUE TITLE
Test: Toolkit preparation  ,Modify path_to/toolkit in lib/core/get_eao.m to your vot-toolkit path

### ISSUE THREAD

**Issue by LiuYaoming666** [researchmm/SiamDW#40]
excuse me ,when i modify the path_to/toolkit in lib/core/get_eao.m, I don't kown (pwd = ['/home/lym/vot-toolkit/','vot-workspace',year]), what is the "vot-workspace"?Can you show me your pwd=?
Thank you very much!

**Comment by JudasDie** [comment]
> excuse me ,when i modify the path_to/toolkit in lib/core/get_eao.m, I don't kown (pwd = ['/home/lym/vot-toolkit/','vot-workspace',year]), what is the "vot-workspace"?Can you show me your pwd=?
> Thank you very much!

Hi~ thanks for your interest. This scripts is used for VOT benchmark, and first you need to read official VOT documents. Then build a VOT workspace namely `vot-workspace2016` or others.

**Comment by LiuYaoming666** [comment]
Thank you .
I will try this.
Thank you very much.

发自我的iPhone


------------------ Original ------------------

**Comment by JudasDie** [comment]
> Thank you . I will try this. Thank you very much. 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: ZP ZHANG <notifications@github.com&gt; Date: Thu,Sep 12,2019 9:53 AM To: researchmm/SiamDW <SiamDW@noreply.github.com&gt; Cc: LiuYaoming666 <814893648@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [researchmm/SiamDW] Test: Toolkit preparation ,Modify path_to/toolkit in lib/core/get_eao.m to your vot-toolkit path (#40)

You are so welcome. If you need other help, pls email me (zhangzhipeng2017@ia.ac.cn).

**Comment by LiuYaoming666** [comment]
You are a so kind man.&nbsp;
Wish you all the best in your work and research.&nbsp;

发自我的iPhone


------------------ Original ------------------
