### ISSUE TITLE
where is script & model for CIResNet-16/19/43?

### ISSUE THREAD

**Issue by LiyaoTang** [researchmm/SiamDW#41]
Thanks for your great works and I found this repo to be really helpful.

Yet, other than the best-performing model CIResNet-22, I am also interested in several variants that's discussed in your paper, including the light-weight CIResNet-16 and the deeper CIResNet-43. However, I did not find the pre-trained model nor the code in the repo.

Could you please also share those models?

Thanks in advance.

**Comment by JudasDie** [comment]
> Thanks for your great works and I found this repo to be really helpful.
> 
> Yet, other than the best-performing model CIResNet-22, I am also interested in several variants that's discussed in your paper, including the light-weight CIResNet-16 and the deeper CIResNet-43. However, I did not find the pre-trained model nor the code in the repo.
> 
> Could you please also share those models?
> 
> Thanks in advance.

Hi~ Thanks for your interest. I will try to find these models in my server (:). Could u leave your email? I'll send it to you later.

**Comment by LiyaoTang** [comment]
Thank you very much! my email is "beihaifusang@gmail.com" :)

**Comment by JudasDie** [comment]
> Thank you very much! my email is "[beihaifusang@gmail.com](mailto:beihaifusang@gmail.com)" :)

You are some welcome. I'll send it to you asap. If you have other questions, please email me zhangzhipeng2017@ia.ac.cn.
