### ISSUE TITLE
About PAIRS: 600000

### ISSUE THREAD

**Issue by zlj199502** [researchmm/SiamDW#42]
Hi, Thank you for your excellent work. I have a quetion about PAIRS. Why is it set to 600000?

**Comment by JudasDie** [comment]
> Hi, Thank you for your excellent work. I have a quetion about PAIRS. Why is it set to 600000?

Hi~ Thanks for your interest. You can do some ablations to decide the optimal number. For example, it is enough for FC-based module with only 20w pairs on GOT10K.
