### ISSUE TITLE
last step of test

### ISSUE THREAD

**Issue by han3889847** [researchmm/SiamDW#44]
when I try to analysis testing results i meet some errors that is

![image](https://user-images.githubusercontent.com/45353049/66103145-679c1880-e5e7-11e9-896d-5049b5ee781e.png)

and i don't know how to modify my get_eao.m ,can you show me how to modify it.especially what meaning of 'year‘　in pwd = ['/home/han/project/vot-toolkit/', 'vot-workspace/', 'year']  % year is a str (can not be a number)

**Comment by JudasDie** [comment]
> when I try to analysis testing results i meet some errors that is
> 
> ![image](https://user-images.githubusercontent.com/45353049/66103145-679c1880-e5e7-11e9-896d-5049b5ee781e.png)
> 
> and i don't know how to modify my get_eao.m ,can you show me how to modify it.especially what meaning of 'year‘　in pwd = ['/home/han/project/vot-toolkit/', 'vot-workspace/', 'year'] % year is a str (can not be a number)

Hi~
Thanks for your interest. I have already provided a script namely `get_eao.m` in `lib/core`. Pls feel free to use it. In general, we create vot-toolkit worksapce namely `vot-workspace201x`. So the `year` means this directory name. Pls check vot offical installing toolkit tutorial.

**Comment by han3889847** [comment]
Thank you for your prompt reply！I'll try it.
