### ISSUE TITLE
在运行get_eao的时候，出现unrecognized argument 

### ISSUE THREAD

**Issue by haodongze** [researchmm/SiamDW#45]

**Comment by JudasDie** [comment]
> _No description provided._

Please modify `workspace_load.m` in vot-toolkit. Set the input to `pwd` in `get_eao.m`.

**Comment by xujiao3628** [comment]
> > _No description provided._
> 
> Please modify `workspace_load.m` in vot-toolkit. Set the input to `pwd` in `get_eao.m`.

hello,I meet the same question, sorry, I don't understand what you said. could you please say it in detail.

**Comment by JudasDie** [comment]
> > > _No description provided._
> > 
> > 
> > Please modify `workspace_load.m` in vot-toolkit. Set the input to `pwd` in `get_eao.m`.
> 
> hello,I meet the same question, sorry, I don't understand what you said. could you please say it in detail.

Thanks for your interst. I'll upload a `workspace_load.m` to `libs/core/`. Please replace the original script from vot-toolkit with our version.

**Comment by JudasDie** [comment]
> > > _No description provided._
> > 
> > 
> > Please modify `workspace_load.m` in vot-toolkit. Set the input to `pwd` in `get_eao.m`.
> 
> hello,I meet the same question, sorry, I don't understand what you said. could you please say it in detail.

I have uploaded the modified `workspace_load.m`. If you have other questions, pls be free to email me zhangzhipeng2017@ia.ac.cn.
