### ISSUE TITLE
About the groundtruth in GOT10K's json.

### ISSUE THREAD

**Issue by kasuo511** [researchmm/SiamDW#47]
Thanks for sharing your code. I noticed that the groundtruth in GOT10K's json file is much bigger than the resolution of GOT10K's train pictures. The resolution is 127*127 and 255*255, but the gt is more like [344, 223, 776, 1002]. I have no idea how it comes, can you please explain it?

**Comment by JudasDie** [comment]
> Thanks for sharing your code. I noticed that the groundtruth in GOT10K's json file is much bigger than the resolution of GOT10K's train pictures. The resolution is 127_127 and 255_255, but the gt is more like [344, 223, 776, 1002]. I have no idea how it comes, can you please explain it?

Thanks for your interest. [344, 223, 776, 1002] refers to the gt box on the original image instead of the input of Siamese net.

**Comment by kasuo511** [comment]
Then how can I get to know the original image's size? They do not seem to be in the dataset folder or in json file, but the training code runs correctly.

**Comment by JudasDie** [comment]
> Then how can I get to know the original image's size? They do not seem to be in the dataset folder or in json file, but the training code runs correct
There is no need to know original image's size to train SiamNet, since all objects are centered at the pairs.

**Comment by kasuo511** [comment]
So whats the point of these functions:` _get_image_anno(self, video, track, frame):` 
and 
`def _get_pairs(self, index):`
code from module.py. It returns every image's path and annotation. What is it for?

**Comment by JudasDie** [comment]
> So whats the point of these functions:` _get_image_anno(self, video, track, frame):`
> and
> `def _get_pairs(self, index):`
> code from module.py. It returns every image's path and annotation. What is it for?

The width and height of an object are utilized to calculate `delta` for RPN training.

**Comment by kasuo511** [comment]
Thank you for your patience. 
At last, I would like to ask some pretrained  models.
Could you please provide the CIResNet19_RPN and CIResNet16_RPN 's pretrained models?

**Comment by JudasDie** [comment]
> Thank you for your patience.
> At last, I would like to ask some pretrained models.
> Could you please provide the CIResNet19_RPN and CIResNet16_RPN 's pretrained models?

You're so welcome. They share same pretrained models with CIRes22.

**Comment by kasuo511** [comment]
Or do you mind sharing the trained models for CIResNet19 and CIResNet16 on RPN, I really interested in several different models that's discussed in your paper.

**Comment by JudasDie** [comment]
> Or do you mind sharing the trained models for CIResNet19 and CIResNet16 on RPN, I really interested in several different models that's discussed in your paper.

Would you mind leave you email? I will send to you later.

**Comment by kasuo511** [comment]
That would be nice,  please email to tianpeng_liu@163.com.
Thanks in advance!

**Comment by JudasDie** [comment]
> That would be nice, please email to [tianpeng_liu@163.com](mailto:tianpeng_liu@163.com).
> Thanks in advance!

You are welcome.
