### ISSUE TITLE
issues about datasets

### ISSUE THREAD

**Issue by JackDance** [researchmm/SiamDW#48]
who can share the VID, YTB, GOT10K, COCO, DET and LASOT according to baiduyun? they are so huge and difficult to download in domestic. can share a baiduyun link ?thanks so much!

**Comment by JudasDie** [comment]
> who can share the VID, YTB, GOT10K, COCO, DET and LASOT according to baiduyun? they are so huge and difficult to download in domestic. can share a baiduyun link ?thanks so much!

Hi, thanks for your interest. Sorry to say I couldn't upload all the data to BaiduDrive because of some limitations (space, speed, size ...).  Could you find a VPN to download it from GoogleDrive?

**Comment by JudasDie** [comment]
> who can share the VID, YTB, GOT10K, COCO, DET and LASOT according to baiduyun? they are so huge and difficult to download in domestic. can share a baiduyun link ?thanks so much!

Hi, have you fixed your problem?

**Comment by JackDance** [comment]
Hi，thank you for your reply，I have fixed ，thanks!




| |
张路遥
|
|
邮箱：jack_zhangluyao@163.com
|

签名由 网易邮箱大师 定制

On 12/11/2019 11:09, ZP ZHANG wrote:

who can share the VID, YTB, GOT10K, COCO, DET and LASOT according to baiduyun? they are so huge and difficult to download in domestic. can share a baiduyun link ?thanks so much!

Hi, have you fixed your problem?

**Comment by jianjiandandande** [comment]
Can you share your datas to me? It is so big and I don't have enough VPN traffic.Sorry

**Comment by JudasDie** [comment]
> Can you share your datas to me? It is so big and I don't have enough VPN traffic.Sorry

Sorry for my late reply. Have you get the data?

**Comment by jianjiandandande** [comment]
No, I just read the paper.

**Comment by JudasDie** [comment]
> No, I just read the paper.

Please find download link in `readme.md` and `train.md`.
