### ISSUE TITLE
opencv-python=3.1.0.5 cannot be installed

### ISSUE THREAD

**Issue by FHCGIT** [researchmm/SiamDW#49]
ERROR: Could not find a version that satisfies the requirement opencv-python==3.1.0.5 (from versions: 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 4.0.0.21, 4.0.1.23, 4.0.1.24, 4.1.0.25, 4.1.1.26)
ERROR: No matching distribution found for opencv-python==3.1.0.5
Could you help me to fix it?

**Comment by JudasDie** [comment]
> ERROR: Could not find a version that satisfies the requirement opencv-python==3.1.0.5 (from versions: 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 4.0.0.21, 4.0.1.23, 4.0.1.24, 4.1.0.25, 4.1.1.26)
> ERROR: No matching distribution found for opencv-python==3.1.0.5
> Could you help me to fix it?

Thanks for your interest. You may try other 3.x versions, but I could't promise you that they performs exactly the same as 3.1.0.5 version. BTW, why there is no 3.1.0.5 to choose? Linux version maybe?

**Comment by FHCGIT** [comment]
Thank you for your reply, it runs on ubuntu and the AUC performance on the OTB-2013 is about 0.63

**Comment by JudasDie** [comment]
> Thank you for your reply, it runs on ubuntu and the AUC performance on the OTB-2013 is about 0.63

If the hyper-parameter is loaded (please double check here), then the testing environmrnt is account for this misalignment. Could you pls try to compile source file or use anaconda to install? Otherwise, you have to tune the hyper-parameters in you testing environment.

**Comment by JudasDie** [comment]
> > Thank you for your reply, it runs on ubuntu and the AUC performance on the OTB-2013 is about 0.63
> 
> If the hyper-parameter is loaded (please double check here), then the testing environmrnt is account for this misalignment. Could you pls try to compile source file or use anaconda to install? Otherwise, you have to tune the hyper-parameters in you testing environment.

Hi, have you fixed the problem?

**Comment by FHCGIT** [comment]
Yes, I fix it on the win10 system. Thank you very much!!!

**Comment by JudasDie** [comment]
> Yes, I fix it on the win10 system. Thank you very much!!!

Glad to help you. If you have other questions, feel free to email me.
