### ISSUE TITLE
How long will it take to train a simaseFC with CIResNet22, 2 1080Ti GPUs, dataset VID.

### ISSUE THREAD

**Issue by kalyo-zjl** [researchmm/SiamDW#51]
Hi, thanks for sharing the code.
I found the estimated time in my machine is about several days, and most of the time-consuming stage is Data Time.
Is this reasonable?

**Comment by JudasDie** [comment]
> Hi, thanks for sharing the code.
> I found the estimated time in my machine is about several days, and most of the time-consuming stage is Data Time.
> Is this reasonable?

Hi, thanks for your interest, and sorry to reply late. The data loding time is limited to hard disk. You should use SSD or PCIE to store training data.

**Comment by JudasDie** [comment]
> Hi, thanks for sharing the code.
> I found the estimated time in my machine is about several days, and most of the time-consuming stage is Data Time.
> Is this reasonable?

Hi, is there anything else I can help you?
