### ISSUE TITLE
test on VOT2018 meet errors

### ISSUE THREAD

**Issue by alyssa121** [researchmm/SiamDW#52]
then I add some code in SiamRPN22.yaml file:
`TEST:
  VOT2015:
    penalty_k: 0.8950
    lr: 0.6540
    window_influence: 0.3700
  VOT2016:
    penalty_k: 0.7110
    lr: 0.7010
    window_influence: 0.3550
  VOT2017:
    penalty_k: 0.038
    lr: 0.388
    window_influence: 0.347
  VOT2018:
    PENALTY_K: 0.05
    WINDOW_INFLUENCE: 0.42
    LR: 0.38
`
what else should I do to modify the code, so that I can test use VOT2018 dataset?
I'm looking forward to your reply, thanks

**Comment by JudasDie** [comment]
> then I add some code in SiamRPN22.yaml file:
> `TEST: VOT2015: penalty_k: 0.8950 lr: 0.6540 window_influence: 0.3700 VOT2016: penalty_k: 0.7110 lr: 0.7010 window_influence: 0.3550 VOT2017: penalty_k: 0.038 lr: 0.388 window_influence: 0.347 VOT2018: PENALTY_K: 0.05 WINDOW_INFLUENCE: 0.42 LR: 0.38 `
> what else should I do to modify the code, so that I can test use VOT2018 dataset?
> I'm looking forward to your reply, thanks

Hi~ Thanks for your interest.  Is there any bug if you directly test it on  VOT2018?

**Comment by JudasDie** [comment]
> then I add some code in SiamRPN22.yaml file:
> `TEST: VOT2015: penalty_k: 0.8950 lr: 0.6540 window_influence: 0.3700 VOT2016: penalty_k: 0.7110 lr: 0.7010 window_influence: 0.3550 VOT2017: penalty_k: 0.038 lr: 0.388 window_influence: 0.347 VOT2018: PENALTY_K: 0.05 WINDOW_INFLUENCE: 0.42 LR: 0.38 `
> what else should I do to modify the code, so that I can test use VOT2018 dataset?
> I'm looking forward to your reply, thanks

Hi, have you fixed the problem?

**Comment by alyssa121** [comment]
> > then I add some code in SiamRPN22.yaml file:
> > `TEST: VOT2015: penalty_k: 0.8950 lr: 0.6540 window_influence: 0.3700 VOT2016: penalty_k: 0.7110 lr: 0.7010 window_influence: 0.3550 VOT2017: penalty_k: 0.038 lr: 0.388 window_influence: 0.347 VOT2018: PENALTY_K: 0.05 WINDOW_INFLUENCE: 0.42 LR: 0.38 `
> > what else should I do to modify the code, so that I can test use VOT2018 dataset?
> > I'm looking forward to your reply, thanks
> 
> Hi, have you fixed the problem?

Sorry for late reply. I hadn't run the code since I met errors.
