### ISSUE TITLE
特定跟踪目标

### ISSUE THREAD

**Issue by summerwbb** [researchmm/SiamDW#56]
你好，我在您的预训练模型上测试了我的数据集，我想实现人头的跟踪，但是发现当连续帧跟错的时候会出现一直跟着错误的物体（胳膊等），因此我想问一下我能不能只训练人头的模型，这样实现只跟踪人头。

**Comment by JudasDie** [comment]
> 你好，我在您的预训练模型上测试了我的数据集，我想实现人头的跟踪，但是发现当连续帧跟错的时候会出现一直跟着错误的物体（胳膊等），因此我想问一下我能不能只训练人头的模型，这样实现只跟踪人头。

你好， 感谢关注我们的工作。这个可以实现的。我的建议是：1）加载我们的model作为预训练模型， 然后在你自己的数据集上面微调； 2）学习率要设置的稍微小一点； 3）微调时候不要把所有层都释放，FC只释放最后一个block，RPN固定所有的backbone；4）如果人头尺度变化不大的话用FC，如果变化尺度大的话用RPN；5) 对于跟踪器跟丢，建议你加入re-id等策略重新找回。

**Comment by summerwbb** [comment]
我能用您的代码简单的实现多个人头的跟踪吗？不需要人头id识别，只需要不丢帧就行。

**Comment by JudasDie** [comment]
> 我能用您的代码简单的实现多个人头的跟踪吗？不需要人头id识别，只需要不丢帧就行。
代码是针对单目标的，建议你把我们tracker套到多目标跟踪的框架里面。

**Comment by JudasDie** [comment]
> 我能用您的代码简单的实现多个人头的跟踪吗？不需要人头id识别，只需要不丢帧就行。

Hi, is there anything else that I can help you?
