### ISSUE TITLE
questions about coco dataset

### ISSUE THREAD

**Issue by QIQIVTrackingY** [researchmm/SiamDW#57]
Hello, the size of search images of coco is 511 and template is 127 ,but others is 255 and 127. When training with coco, i need to set size of search iamges to 511 and size of template to 127  ? Do i need to train with coco lonly?

**Comment by JudasDie** [comment]
> Hello, the size of search images of coco is 511 and template is 127 ,but others is 255 and 127. When training with coco, i need to set size of search iamges to 511 and size of template to 127 ? Do i need to train with coco lonly?

Hi, thanks for your interest. Please set search image to 255 for all datasets. The program will automatically crop it.

**Comment by JudasDie** [comment]
> > Hello, the size of search images of coco is 511 and template is 127 ,but others is 255 and 127. When training with coco, i need to set size of search iamges to 511 and size of template to 127 ? Do i need to train with coco lonly?
> 
> Hi, thanks for your interest. Please set search image to 255 for all datasets. The program will automatically crop it.

Hi, have you fixed the problem?

**Comment by QIQIVTrackingY** [comment]
Yes,thank you!



---Original---
