### ISSUE TITLE
some problems about training

### ISSUE THREAD

**Issue by lipeng-gu** [researchmm/SiamDW#58]
Thank you for your sharing, but i have some problems about training.
1) i find that the training process is a little complicated. If I want to modify the network, such as backbone, or the network of  classification branch, how to retrain the model?
2) if i want to retrain the model, what datasets should i use to train the model.
3) By reading paper, i know that SiamRPN are trained on  ImageNet VID and Youtube-BB. Where can i download these two datasets.

**Comment by JudasDie** [comment]
> Thank you for your sharing, but i have some problems about training.
> 
> 1. i find that the training process is a little complicated. If I want to modify the network, such as backbone, or the network of  classification branch, how to retrain the model?
> 2. if i want to retrain the model, what datasets should i use to train the model.
> 3. By reading paper, i know that SiamRPN are trained on  ImageNet VID and Youtube-BB. Where can i download these two datasets.

Hi, thanks for your interest.
1. You can modify each component in `models` directory.
2. You can use the default data in the code.
3. We provide 6 data in the GoogleDrive, and you can find the download link in `train.md`.  You can also make your dataset with the provided cropping scripts.

**Comment by lipeng-gu** [comment]
> > Thank you for your sharing, but i have some problems about training.
> > 
> > 1. i find that the training process is a little complicated. If I want to modify the network, such as backbone, or the network of  classification branch, how to retrain the model?
> > 2. if i want to retrain the model, what datasets should i use to train the model.
> > 3. By reading paper, i know that SiamRPN are trained on  ImageNet VID and Youtube-BB. Where can i download these two datasets.
> 
> Hi, thanks for your interest.
> 
> 1. You can modify each component in `models` directory.
> 2. You can use the default data in the code.
> 3. We provide 6 data in the GoogleDrive, and you can find the download link in `train.md`.  You can also make your dataset with the provided cropping scripts.

@JudasDie 
thank you for your reply!
1. can i use only one of copy of `_coco.tar, copy of det.tar, copy of siamdw_data.zip, lasot.zip and y2b.zip_` to  train modified network?  for example, can i only use copy of siamdw_data.zip to train modified network? i don't know if i can get a better result.
2. if i modify the RPN part of the network, can i use the provided pre-training model to train the modified network?

**Comment by JudasDie** [comment]
> > > Thank you for your sharing, but i have some problems about training.
> > > 
> > > 1. i find that the training process is a little complicated. If I want to modify the network, such as backbone, or the network of  classification branch, how to retrain the model?
> > > 2. if i want to retrain the model, what datasets should i use to train the model.
> > > 3. By reading paper, i know that SiamRPN are trained on  ImageNet VID and Youtube-BB. Where can i download these two datasets.
> > 
> > 
> > Hi, thanks for your interest.
> > 
> > 1. You can modify each component in `models` directory.
> > 2. You can use the default data in the code.
> > 3. We provide 6 data in the GoogleDrive, and you can find the download link in `train.md`.  You can also make your dataset with the provided cropping scripts.
> 
> @JudasDie
> thank you for your reply!
> 
> 1. can i use only one of copy of `_coco.tar, copy of det.tar, copy of siamdw_data.zip, lasot.zip and y2b.zip_` to  train modified network?  for example, can i only use copy of siamdw_data.zip to train modified network? i don't know if i can get a better result.
> 2. if i modify the RPN part of the network, can i use the provided pre-training model to train the modified network?

1.  If you want to train SiamFC, GOT10K is enough. If you want to train RPN, I think you should use as many as you can.
2. If you don't modify backbone part, that is ok.

**Comment by lipeng-gu** [comment]
> > > > Thank you for your sharing, but i have some problems about training.
> > > > 
> > > > 1. i find that the training process is a little complicated. If I want to modify the network, such as backbone, or the network of  classification branch, how to retrain the model?
> > > > 2. if i want to retrain the model, what datasets should i use to train the model.
> > > > 3. By reading paper, i know that SiamRPN are trained on  ImageNet VID and Youtube-BB. Where can i download these two datasets.
> > > 
> > > 
> > > Hi, thanks for your interest.
> > > 
> > > 1. You can modify each component in `models` directory.
> > > 2. You can use the default data in the code.
> > > 3. We provide 6 data in the GoogleDrive, and you can find the download link in `train.md`.  You can also make your dataset with the provided cropping scripts.
> > 
> > 
> > @JudasDie
> > thank you for your reply!
> > 
> > 1. can i use only one of copy of `_coco.tar, copy of det.tar, copy of siamdw_data.zip, lasot.zip and y2b.zip_` to  train modified network?  for example, can i only use copy of siamdw_data.zip to train modified network? i don't know if i can get a better result.
> > 2. if i modify the RPN part of the network, can i use the provided pre-training model to train the modified network?
> 
> 1. If you want to train SiamFC, GOT10K is enough. If you want to train RPN, I think you should use as many as you can.
> 2. If you don't modify backbone part, that is ok.

@JudasDie 
thank you for your reply!
i try both of SiamFC and SiamRPN, i think that SiamRPN is faster and more accurate than SiamFC. So, i am willing to use SiamRPN. 
1. Datasets are quite large, how many datasets do you think i need to use to train SiamRPN?
2. if several datasets are used, are they merged into one folder or store them in different paths?
3. i've seen from other blogs how to load a pre-training model for a modified network. for example,
`#加载model
resnet50 = models.resnet50(pretrained=True)
cnn = CNN(Bottleneck, [3, 4, 6, 3])
#读取参数
pretrained_dict = resnet50.state_dict()
model_dict = cnn.state_dict()
# 将pretrained_dict里不属于model_dict的键剔除掉
pretrained_dict =  {k: v for k, v in pretrained_dict.items() if k in model_dict}
# 更新现有的model_dict
model_dict.update(pretrained_dict)
# 加载我们真正需要的state_dict
cnn.load_state_dict(model_dict)`
i can use this method to load the pre-training model to train modified network, if i only modify the RPN part of network.

**Comment by JudasDie** [comment]
> > > > > Thank you for your sharing, but i have some problems about training.
> > > > > 
> > > > > 1. i find that the training process is a little complicated. If I want to modify the network, such as backbone, or the network of  classification branch, how to retrain the model?
> > > > > 2. if i want to retrain the model, what datasets should i use to train the model.
> > > > > 3. By reading paper, i know that SiamRPN are trained on  ImageNet VID and Youtube-BB. Where can i download these two datasets.
> > > > 
> > > > 
> > > > Hi, thanks for your interest.
> > > > 
> > > > 1. You can modify each component in `models` directory.
> > > > 2. You can use the default data in the code.
> > > > 3. We provide 6 data in the GoogleDrive, and you can find the download link in `train.md`.  You can also make your dataset with the provided cropping scripts.
> > > 
> > > 
> > > @JudasDie
> > > thank you for your reply!
> > > 
> > > 1. can i use only one of copy of `_coco.tar, copy of det.tar, copy of siamdw_data.zip, lasot.zip and y2b.zip_` to  train modified network?  for example, can i only use copy of siamdw_data.zip to train modified network? i don't know if i can get a better result.
> > > 2. if i modify the RPN part of the network, can i use the provided pre-training model to train the modified network?
> > 
> > 
> > 
> > 1. If you want to train SiamFC, GOT10K is enough. If you want to train RPN, I think you should use as many as you can.
> > 2. If you don't modify backbone part, that is ok.
> 
> @JudasDie
> thank you for your reply!
> i try both of SiamFC and SiamRPN, i think that SiamRPN is faster and more accurate than SiamFC. So, i am willing to use SiamRPN.
> 
> 1. Datasets are quite large, how many datasets do you think i need to use to train SiamRPN?
> 2. if several datasets are used, are they merged into one folder or store them in different paths?
> 3. i've seen from other blogs how to load a pre-training model for a modified network. for example,
>    `#加载model
>    resnet50 = models.resnet50(pretrained=True)
>    cnn = CNN(Bottleneck, [3, 4, 6, 3])
>    #读取参数
>    pretrained_dict = resnet50.state_dict()
>    model_dict = cnn.state_dict()
> 
> # 将pretrained_dict里不属于model_dict的键剔除掉
> pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict}
> 
> # 更新现有的model_dict
> model_dict.update(pretrained_dict)
> 
> # 加载我们真正需要的state_dict
> cnn.load_state_dict(model_dict)`
> i can use this method to load the pre-training model to train modified network, if i only modify the RPN part of network.

1) As mentioned, use as many as u can. Or keep default settings.
2) See `yaml` files in `experiments/train` to decide how to put dataset.
3) Pytorch save and load models in `dict` format, so just keep same keys between model and checkpoint.

**Comment by lipeng-gu** [comment]
> > > > > > Thank you for your sharing, but i have some problems about training.
> > > > > > 
> > > > > > 1. i find that the training process is a little complicated. If I want to modify the network, such as backbone, or the network of  classification branch, how to retrain the model?
> > > > > > 2. if i want to retrain the model, what datasets should i use to train the model.
> > > > > > 3. By reading paper, i know that SiamRPN are trained on  ImageNet VID and Youtube-BB. Where can i download these two datasets.
> > > > > 
> > > > > 
> > > > > Hi, thanks for your interest.
> > > > > 
> > > > > 1. You can modify each component in `models` directory.
> > > > > 2. You can use the default data in the code.
> > > > > 3. We provide 6 data in the GoogleDrive, and you can find the download link in `train.md`.  You can also make your dataset with the provided cropping scripts.
> > > > 
> > > > 
> > > > @JudasDie
> > > > thank you for your reply!
> > > > 
> > > > 1. can i use only one of copy of `_coco.tar, copy of det.tar, copy of siamdw_data.zip, lasot.zip and y2b.zip_` to  train modified network?  for example, can i only use copy of siamdw_data.zip to train modified network? i don't know if i can get a better result.
> > > > 2. if i modify the RPN part of the network, can i use the provided pre-training model to train the modified network?
> > > 
> > > 
> > > 
> > > 1. If you want to train SiamFC, GOT10K is enough. If you want to train RPN, I think you should use as many as you can.
> > > 2. If you don't modify backbone part, that is ok.
> > 
> > 
> > @JudasDie
> > thank you for your reply!
> > i try both of SiamFC and SiamRPN, i think that SiamRPN is faster and more accurate than SiamFC. So, i am willing to use SiamRPN.
> > 
> > 1. Datasets are quite large, how many datasets do you think i need to use to train SiamRPN?
> > 2. if several datasets are used, are they merged into one folder or store them in different paths?
> > 3. i've seen from other blogs how to load a pre-training model for a modified network. for example,
> >    `#加载model
> >    resnet50 = models.resnet50(pretrained=True)
> >    cnn = CNN(Bottleneck, [3, 4, 6, 3])
> >    #读取参数
> >    pretrained_dict = resnet50.state_dict()
> >    model_dict = cnn.state_dict()
> > 
> > # 将pretrained_dict里不属于model_dict的键剔除掉
> > pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict}
> > # 更新现有的model_dict
> > model_dict.update(pretrained_dict)
> > # 加载我们真正需要的state_dict
> > cnn.load_state_dict(model_dict)`
> > i can use this method to load the pre-training model to train modified network, if i only modify the RPN part of network.
> 
> 1. As mentioned, use as many as u can. Or keep default settings.
> 2. See `yaml` files in `experiments/train` to decide how to put dataset.
> 3. Pytorch save and load models in `dict` format, so just keep same keys between model and checkpoint.

@JudasDie 
thank you for your reply！

**Comment by JudasDie** [comment]
> > > > > > > Thank you for your sharing, but i have some problems about training.
> > > > > > > 
> > > > > > > 1. i find that the training process is a little complicated. If I want to modify the network, such as backbone, or the network of  classification branch, how to retrain the model?
> > > > > > > 2. if i want to retrain the model, what datasets should i use to train the model.
> > > > > > > 3. By reading paper, i know that SiamRPN are trained on  ImageNet VID and Youtube-BB. Where can i download these two datasets.
> > > > > > 
> > > > > > 
> > > > > > Hi, thanks for your interest.
> > > > > > 
> > > > > > 1. You can modify each component in `models` directory.
> > > > > > 2. You can use the default data in the code.
> > > > > > 3. We provide 6 data in the GoogleDrive, and you can find the download link in `train.md`.  You can also make your dataset with the provided cropping scripts.
> > > > > 
> > > > > 
> > > > > @JudasDie
> > > > > thank you for your reply!
> > > > > 
> > > > > 1. can i use only one of copy of `_coco.tar, copy of det.tar, copy of siamdw_data.zip, lasot.zip and y2b.zip_` to  train modified network?  for example, can i only use copy of siamdw_data.zip to train modified network? i don't know if i can get a better result.
> > > > > 2. if i modify the RPN part of the network, can i use the provided pre-training model to train the modified network?
> > > > 
> > > > 
> > > > 
> > > > 1. If you want to train SiamFC, GOT10K is enough. If you want to train RPN, I think you should use as many as you can.
> > > > 2. If you don't modify backbone part, that is ok.
> > > 
> > > 
> > > @JudasDie
> > > thank you for your reply!
> > > i try both of SiamFC and SiamRPN, i think that SiamRPN is faster and more accurate than SiamFC. So, i am willing to use SiamRPN.
> > > 
> > > 1. Datasets are quite large, how many datasets do you think i need to use to train SiamRPN?
> > > 2. if several datasets are used, are they merged into one folder or store them in different paths?
> > > 3. i've seen from other blogs how to load a pre-training model for a modified network. for example,
> > >    `#加载model
> > >    resnet50 = models.resnet50(pretrained=True)
> > >    cnn = CNN(Bottleneck, [3, 4, 6, 3])
> > >    #读取参数
> > >    pretrained_dict = resnet50.state_dict()
> > >    model_dict = cnn.state_dict()
> > > 
> > > # 将pretrained_dict里不属于model_dict的键剔除掉
> > > pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict}
> > > # 更新现有的model_dict
> > > model_dict.update(pretrained_dict)
> > > # 加载我们真正需要的state_dict
> > > cnn.load_state_dict(model_dict)`
> > > i can use this method to load the pre-training model to train modified network, if i only modify the RPN part of network.
> > 
> > 
> > 
> > 1. As mentioned, use as many as u can. Or keep default settings.
> > 2. See `yaml` files in `experiments/train` to decide how to put dataset.
> > 3. Pytorch save and load models in `dict` format, so just keep same keys between model and checkpoint.
> 
> @JudasDie
> thank you for your reply！

Glad that I can help you.
