### ISSUE TITLE
Environment requirements to run demo

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [researchmm/SiamDW#60]
Hi, 
    Can you tell about required environment setting i.e Cuda  + cudnn + opnecv versions and required libraries i.e  TensorFlow or Pytorch or any other necessary libraries need to install before running the demo?

**Comment by JudasDie** [comment]
> Hi,
> Can you tell about required environment setting i.e Cuda + cudnn + opnecv versions and required libraries i.e TensorFlow or Pytorch or any other necessary libraries need to install before running the demo?

Hi, thanks for your interest. You can read `install.sh` and `install_rpn` to find details.

**Comment by MuhammadAsadJaved** [comment]
@JudasDie  OK. Thank you for your response.
