### ISSUE TITLE
Add to PySOT ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [researchmm/SiamDW#63]
Is there a hope to add SiamDW to the [PySOT](https://github.com/STVIR/pysot) Repo for ease of use ?

**Comment by JudasDie** [comment]
> Is there a hope to add SiamDW to the [PySOT](https://github.com/STVIR/pysot) Repo for ease of use ?

Hi, thanks for your interest. New code and better model with Pysot is already on schedule.
