### ISSUE TITLE
The problem about cropped images size 271

### ISSUE THREAD

**Issue by ZZXin** [researchmm/SiamDW#64]
Why the crop size during preprocessing is 271, and  is there  difference with  511 in pysot？

**Comment by JudasDie** [comment]
> Why the crop size during preprocessing is 271, and is there difference with 511 in pysot？

Hi, the dataloader will handle it. The size of the input image is casual (271 or 255). You donot need to worry about that.

**Comment by ZZXin** [comment]
> > Why the crop size during preprocessing is 271, and is there difference with 511 in pysot？
> 
> Hi, the dataloader will handle it. The size of the input image is casual (271 or 255). You donot need to worry about that.

Thanks for your quick reply,Thanks for your job,Truely.

**Comment by JudasDie** [comment]
> > > Why the crop size during preprocessing is 271, and is there difference with 511 in pysot？
> > 
> > 
> > Hi, the dataloader will handle it. The size of the input image is casual (271 or 255). You donot need to worry about that.
> 
> Thanks for your quick reply,Thanks for your job,Truely.

You are so welcome. Hope to see your great work soon.
