### ISSUE TITLE
Error while running demo (run_video.py)

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [researchmm/SiamDW#66]
Hi , 
Question 1.
    After installing required libraries i am trying to run demo on a video file using

python2 siamese_tracking/run_video.py --arch SiamRPNRes22 --resume snapshot/CIResNet22_RPN.pth --video videos/bag.mp4
But it throw following errors. 

from tracker.siamfc import SiamFC
ImportError: No module named tracker.siamfc
from tracker.siamrpn import SiamRPN
ImportError: No module named tracker.siamrpn

I have checked the siamfc.py and siamrpn.py files are there in /lib/tracker/ folder. so i also tried to expand the path   like    ( from lib.tracker.siamfc import SiamFC and same for rpn) but still same erro. 

Question 2.  which python version is required for this project ? as it is not mentioned in install.sh.

**Comment by JudasDie** [comment]
> Hi ,
> Question 1.
> After installing required libraries i am trying to run demo on a video file using
> 
> python2 siamese_tracking/run_video.py --arch SiamRPNRes22 --resume snapshot/CIResNet22_RPN.pth --video videos/bag.mp4
> But it throw following errors.
> 
> from tracker.siamfc import SiamFC
> ImportError: No module named tracker.siamfc
> from tracker.siamrpn import SiamRPN
> ImportError: No module named tracker.siamrpn
> 
> I have checked the siamfc.py and siamrpn.py files are there in /lib/tracker/ folder. so i also tried to expand the path like ( from lib.tracker.siamfc import SiamFC and same for rpn) but still same erro.
> 
> Question 2. which python version is required for this project ? as it is not mentioned in install.sh.

Hi,
1) Do you run `run_video.py` in `$local_path/SiamDW`?
2) I conduct all experiments with python3.6. You can try python2, but I cannot assure you that there is no bugs with python2.

**Comment by MuhammadAsadJaved** [comment]
Yes i am running in SiamDW project root directory.

**Comment by JudasDie** [comment]
> Yes i am running in SiamDW project root directory.

Did you successfully run `test_siamfc.py` or `test_siamrpn.py`?

**Comment by MuhammadAsadJaved** [comment]
I am able to run run_video.py after copying siamfc.py and siamrpn.py files in the siamese_tracking folder. now there is some other problem about some missing libraries . i am trying to resolve it.  I think it is just an import error. it just can not find these two .py files.

**Comment by JudasDie** [comment]
> I am able to run run_video.py after copying siamfc.py and siamrpn.py files in the siamese_tracking folder. now there is some other problem about some missing libraries . i am trying to resolve it. I think it is just an import error. it just can not find these two .py files.

Glad to hear that. I'll check it again later.  BTW, I think there is no need to copy the files. Some configurations may be incorrect in your running.

**Comment by MuhammadAsadJaved** [comment]
I have tried test_siamfc.py  and test_siamrpn.py without copying files again and it show same error.  My project folder name is SiamDW-master   does it matter?  
Here is folders structure. i did not change anything. Just Downloaded .zip from your repo. 
![siam](https://user-images.githubusercontent.com/28862708/71070854-8b1e3a80-21b6-11ea-88ba-747271ada4ca.png)

**Comment by JudasDie** [comment]
> I have tried test_siamfc.py and test_siamrpn.py without copying files again and it show same error. My project folder name is SiamDW-master does it matter?
> Here is folders structure. i did not change anything. Just Downloaded .zip from your repo.
> ![siam](https://user-images.githubusercontent.com/28862708/71070854-8b1e3a80-21b6-11ea-88ba-747271ada4ca.png)

I found a problem in your shown figure,
 Why the project files are in `siamese_tracking` directory?  All files should be placed in `SiamDW` directory (SiamDW_master in your case).

**Comment by MuhammadAsadJaved** [comment]
OK. I'll change. BTW it's the same structure used in your repo. i just downloaded this repo.  
thank you so much for quick response.

**Comment by JudasDie** [comment]
> OK. I'll change. BTW it's the same structure used in your repo. i just downloaded this repo.
> thank you so much for quick response.

You are so welcome. Maybe you could `git clone` this repo and follow the testing leads (run in terminal). If you fix the problem, pls kindly let me know.  If not, I will help you.

**Comment by MuhammadAsadJaved** [comment]
OK. I'll . Stay blessed.

**Comment by MuhammadAsadJaved** [comment]
Hi, 
    I have successfully run the demo after cloning the repo.
I have a suggestion 
The opencv version mentioned in the install_rpn.sh and install_fc.sh (pip install opencv-python==3.1.0.5) show some error. There is no error while using opencv-python==4.1.0.25. So it's better to mention this version in the install document. 

I also have a question. 
Can we save the output file after running on the video? Do you have any options for that or we should write some python code by our self?  for example running on bag.mp4 then save bag_output.mpt

**Comment by JudasDie** [comment]
> Hi,
> I have successfully run the demo after cloning the repo.
> I have a suggestion
> The opencv version mentioned in the install_rpn.sh and install_fc.sh (pip install opencv-python==3.1.0.5) show some error. There is no error while using opencv-python==4.1.0.25. So it's better to mention this version in the install document.
> 
> I also have a question.
> Can we save the output file after running on the video? Do you have any options for that or we should write some python code by our self? for example running on bag.mp4 then save bag_output.mpt

Glad to hear that. 
1) Thanks for your suggestions. The opencv version error is blamed to Anaconda source. If you don't run the code on tracking benchmarks, you can use any version.
2) You can refer to `test_siamfc.py` to see how to save results in .txt files. If you want to save visual results, just add some simple codes (cv2.rectangle/cv2.imwrite... blabla).

**Comment by MuhammadAsadJaved** [comment]
OK. Got it . Thank you so much. BTW I am also in Beijing. Hope to see you sometime and have cooperation in relevant projects.

**Comment by JudasDie** [comment]
> OK. Got it . Thank you so much. BTW I am also in Beijing. Hope to see you sometime and have cooperation in relevant projects.

That sounds great. You can email me (zhangzhipeng2017@ia.ac.cn) for further talk.
