### ISSUE TITLE
Hello, thank you very much for the data set provided by you in Baidu cloud disk, but I can't download it down and can't unzip it. What's the problem? 

### ISSUE THREAD

**Issue by wg7stream** [researchmm/SiamDW#67]
Hello, thank you very much for the data set provided by you in Baidu cloud disk, but I can't download it down and can't unzip it. How to solve this problem？

**Comment by JudasDie** [comment]
> Hello, thank you very much for the data set provided by you in Baidu cloud disk, but I can't download it down and can't unzip it. How to solve this problem？

Hi, you may refer to [issue11](https://github.com/researchmm/SiamDW/issues/11) to fix this problem.

**Comment by wg7stream** [comment]
Thank you very much .

**Comment by JudasDie** [comment]
> Thank you very much .

Glad to help you.
