### ISSUE TITLE
How to improve the tracking?

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [researchmm/SiamDW#68]
Hi, 
    I have a question about improving this method. There is a problem that when two objects are crossing each other the tracker lost the object easily and may start tracking the wrong object. 
For example if we track a person , when another person cross or hide this person , the tracker starts tracking wrong person. We want to use this tracker in end product in real time. Is there any technique or suggestion to over come this problem?

**Comment by JudasDie** [comment]
> Hi,
> I have a question about improving this method. There is a problem that when two objects are crossing each other the tracker lost the object easily and may start tracking the wrong object.
> For example if we track a person , when another person cross or hide this person , the tracker starts tracking wrong person. We want to use this tracker in end product in real time. Is there any technique or suggestion to over come this problem?

Hi, thanks for your interest. Occlusion is a difficult problem in tracking. One advice is that you can update template image in tracking. Another advice is that re-identification and global search may be helpful in this case.

**Comment by MuhammadAsadJaved** [comment]
Ok thank you so much.
