### ISSUE TITLE
could you provide the code of generating the preprocess dataset？

### ISSUE THREAD

**Issue by RogerYu123** [researchmm/SiamDW#7]
First，thanks for your wonderful work！
the download speed of preprocessed dataset is too slow，could you provide the code of generating the preprocess dataset？so that i can generate the dataset myself.

**Comment by RogerYu123** [comment]
or you can provide a sample part of the dataset so that i can write code to generate it myself.

**Comment by JudasDie** [comment]
> or you can provide a sample part of the dataset so that i can write code to generate it myself.

Thank you for your interest. I'll upload a demo recently.

**Comment by JudasDie** [comment]
> 
> 
> First，thanks for your wonderful work！
> the download speed of preprocessed dataset is too slow，could you provide the code of generating the preprocess dataset？so that i can generate the dataset myself.

The script has been uploaded. See [train.md](https://github.com/researchmm/SiamDW/blob/master/lib/tutorials/train.md).
