### ISSUE TITLE
Train on multiple classes?

### ISSUE THREAD

**Issue by tiberium24** [researchmm/SiamDW#70]
Hello,
Does anybody know how we can train a siamese network for multiple classes of objects? Cars, pedestrians etc.

**Comment by JudasDie** [comment]
> Hello,
> Does anybody know how we can train a siamese network for multiple classes of objects? Cars, pedestrians etc.

Hi, thanks for your interest. This is a single object tracker. If you want to modify it to multi-object tracking, you may check whether this model can be inserted into an MOT tracker.
