### ISSUE TITLE
How to print confident?

### ISSUE THREAD

**Issue by vuducnghia** [researchmm/SiamDW#75]
Hi,
I have a question about showing confidence in file "lib/tracker/siamfc.py". Is there any way or suggestion to calculate the confidence for each track?

**Comment by JudasDie** [comment]
> Hi,
> I have a question about showing confidence in file "lib/tracker/siamfc.py". Is there any way or suggestion to calculate the confidence for each track?

Hi, what do you mean `confidence`? I'm a bit confused.
