### ISSUE TITLE
VisDrone Test-Dev Results 

### ISSUE THREAD

**Issue by khaghanijavad** [researchmm/SiamDW#76]
Hi, 

The results that you have published for SiamFCRes22W is on the test-challenge set of VisDrone. Do you have the raw results of your models for test-dev set? 

Thanks.

**Comment by JudasDie** [comment]
> Hi,
> 
> The results that you have published for SiamFCRes22W is on the test-challenge set of VisDrone. Do you have the raw results of your models for test-dev set?
> 
> Thanks.

Hi, please find raw results in `readme.md`
