### ISSUE TITLE
can you tell me the result of SiamDW in VOT2018 and  VOT2016 (trained by COCO, ImageNet DET , ImageNet VID, and YouTube-BoundingBoxes Dataset)? 

### ISSUE THREAD

**Issue by ghost** [researchmm/SiamDW#77]
can you tell me the result of SiamDW in VOT2018 and  VOT2016 (trained by COCO, ImageNet DET , ImageNet VID, and YouTube-BoundingBoxes Dataset)?

**Comment by JudasDie** [comment]
> can you tell me the result of SiamDW in VOT2018 and VOT2016 (trained by COCO, ImageNet DET , ImageNet VID, and YouTube-BoundingBoxes Dataset)?

Sorry. recently we are busy doing other projects.
