### ISSUE TITLE
Publication Date SiamDW_D

### ISSUE THREAD

**Issue by maxizi** [researchmm/SiamDW#78]
Hi folks,

when will the code of SiamDW_D be published? Is there already a planned date?

Thanks in advance,
Max

**Comment by JudasDie** [comment]
> Hi folks,
> 
> when will the code of SiamDW_D be published? Is there already a planned date?
> 
> Thanks in advance,
> Max

Hi, thanks for your interest. You could access codes and models of SiamDW_D, SiamDW_T, SiamDW_LT in this [repo.](https://github.com/researchmm/VOT2019).

**Comment by maxizi** [comment]
Hi,

thanks for the quick reply! That's even better.
