### ISSUE TITLE
can't download all datasets

### ISSUE THREAD

**Issue by hlyj1995** [researchmm/SiamDW#79]
Why do I stop downloading datasets from GoogleDrive to more than 10G? Has anyone encountered this situation?

**Comment by JudasDie** [comment]
> Why do I stop downloading datasets from GoogleDrive to more than 10G? Has anyone encountered this situation?

Hi. This is the VPN problem in my experience.

**Comment by kasuo511** [comment]
> Why do I stop downloading datasets from GoogleDrive to more than 10G? Has anyone encountered this situation?

hi, have you solved the problem? Could  you pls sharing the way you settle this problem . I've meet the same problem

**Comment by JudasDie** [comment]
> > Why do I stop downloading datasets from GoogleDrive to more than 10G? Has anyone encountered this situation?
> 
> hi, have you solved the problem? Could you pls sharing the way you settle this problem . I've meet the same problem
We have upload all dataset to BaiduYun recently. Please find it in our new [repo.](https://github.com/JudasDie/TracKit)
