### ISSUE TITLE
What training set did the model use for getting the LaSOT result?

### ISSUE THREAD

**Issue by wdanc** [researchmm/SiamDW#80]
Hi~Thanks for your great work! I noticed that the LaSOT result was evaluated with the LaSOT testing subset, the LaSOT web says that this type of evaluation protocol is only allow research to leverage the training set of LaSOT to develop trackers. So I would like to ask was your model reporting LaSOT result trained only with training set of LaSOT? 
And thanks again!

**Comment by JudasDie** [comment]
> Hi~Thanks for your great work! I noticed that the LaSOT result was evaluated with the LaSOT testing subset, the LaSOT web says that this type of evaluation protocol is only allow research to leverage the training set of LaSOT to develop trackers. So I would like to ask was your model reporting LaSOT result trained only with training set of LaSOT?
> And thanks again!

Hi. The result is SiamRes22W on its training data. Yes, the LaSOT testing should be trained on it training data. In my experience, the training data and testing data of LaSOT are too similar to overfit. If you want to build a tracker with better generalization performance, please consider to train with other data.

> Hi~Thanks for your great work! I noticed that the LaSOT result was evaluated with the LaSOT testing subset, the LaSOT web says that this type of evaluation protocol is only allow research to leverage the training set of LaSOT to develop trackers. So I would like to ask was your model reporting LaSOT result trained only with training set of LaSOT?
> And thanks again!

Hi. The result is SiamRes22W on its training data. Yes, the LaSOT testing should be trained on it training data. In my experience, the training data and testing data of LaSOT are too similar to overfit. If you want to build a tracker with better generalization performance, please consider to train with other data.
