### ISSUE TITLE
about OTB100.json

### ISSUE THREAD

**Issue by anchor666** [researchmm/SiamDW#81]
hello,Can you provide the baidu cloud link of otb100.json？thankyou

**Comment by JudasDie** [comment]
> hello,Can you provide the baidu cloud link of otb100.json？thankyou


> hello,Can you provide the baidu cloud link of otb100.json？thankyou

Hi. Please download it from [here](https://pan.baidu.com/s/1gtdOF5eA3TRctArhyCqLaQ)  [extraction code: 591p]
