### ISSUE TITLE
Low fps problem, help.

### ISSUE THREAD

**Issue by ahmetybilgin** [researchmm/SiamDW#82]
I tested in my own video file with run_video.py. The output was running **very slowly**. I saw that the code works around 9-14 fps by adding fps calculation code. Is there a solution to improve? Thank you in advance. Target size w=24px h=26px / Video 1920*1080 / A small destination on the map.

**Comment by ahmetybilgin** [comment]
Hi, @JudasDie @penghouwen @zhangliliang @hongyuanyu  I would appreciate if you help. Thanks

**Comment by JudasDie** [comment]
> Hi, @JudasDie @penghouwen @zhangliliang @hongyuanyu I would appreciate if you help. Thanks

Hi. Could you provide the experiment environment? Besides, which model do you use?

**Comment by ahmetybilgin** [comment]
I worked on run_video.py. I ran it as you said, "python siamese_tracking / run_video.py --arch SiamRPNRes22 --resume snapshot / CIResNet22_RPN.pth - video videos / video1.mp4"

**Comment by ahmetybilgin** [comment]
I installed the normal install_rpn.sh file for environment via Anaconda. I work at local.

**Comment by JudasDie** [comment]
> I worked on run_video.py. I ran it as you said, "python siamese_tracking / run_video.py --arch SiamRPNRes22 --resume snapshot / CIResNet22_RPN.pth - video videos / video1.mp4"

Could you please check whether the code counts the video parsing time? And what GPU do you use?

**Comment by ahmetybilgin** [comment]
Such a short code , print('track speed {:.1f}fps '.format((framecounter-1) / (toc/cv2.getTickFrequency())))
GPU: 840M cuda:10.1

**Comment by JudasDie** [comment]
> Such a short code , print('track speed {:.1f}fps '.format((framecounter-1) / (toc/cv2.getTickFrequency())))
> GPU: 840M cuda:10.1

The GPU may be the reason of your issue. We use GTX1080 for the experiment.

**Comment by ahmetybilgin** [comment]
I saw that GTX1080 was used as gpu, but I didn't think there would be so many performance differences. While the code is running, I use Gpu at around 55%.

**Comment by JudasDie** [comment]
> I saw that GTX1080 was used as gpu, but I didn't think there would be so many performance differences. While the code is running, I use Gpu at around 55%.

I think the GPU capability between 840M and 1080 is large. 840M is in the laptop right? Besides, please see SSD/PCIE to save data.

**Comment by JudasDie** [comment]
> I saw that GTX1080 was used as gpu, but I didn't think there would be so many performance differences. While the code is running, I use Gpu at around 55%.

I think the GPU capability between 840M and 1080 is large. 840M is in the laptop right? Besides, please use SSD/PCIE to save data.

**Comment by ahmetybilgin** [comment]
Thank you for everything. Excellent work.

**Comment by JudasDie** [comment]
> Thank you for everything. Excellent work.

Thanks a lot.
