### ISSUE TITLE
fps of CIResNet22W-FC？

### ISSUE THREAD

**Issue by herbert-chen** [researchmm/SiamDW#85]
感谢大佬的工作，感觉你们的CIResNet22W-FC性能很强，但是论文中似乎没有提到，请问它的fps是多少呢？

**Comment by JudasDie** [comment]
> 感谢大佬的工作，感觉你们的CIResNet22W-FC性能很强，但是论文中似乎没有提到，请问它的fps是多少呢？

感谢关注哈。这个模型在论文没有，是后期补充到代码里面的。速度约50-60fps在1080Ti.

**Comment by laisimiao** [comment]
CIResNet22FC_G是代表哪个网络模型呀？short time的只有这一个预训练模型吗？

**Comment by JudasDie** [comment]
> CIResNet22FC_G是代表哪个网络模型呀？short time的只有这一个预训练模型吗？

G代表在GOT10K上训练出来的。训练好的模型在test.md下载链接里有。

**Comment by laisimiao** [comment]
In [train.md/Pretrained model preparation](https://github.com/researchmm/SiamDW/blob/master/lib/tutorials/train.md#pretrained-model-preparation) you provided the network pretrained model in ImageNet, for instance, for getting pretrained CIResNet22, you constructed the model and trained them in ImageNet from scratch? Am I right?
