### ISSUE TITLE
Can't download y2b

### ISSUE THREAD

**Issue by ISosnovik** [researchmm/SiamDW#91]
I can't download y2b.zip from your google drive. It says "quota exceeded". Seems like there are some restrictions from your side. Could you resolve it?

**Comment by JudasDie** [comment]
> I can't download y2b.zip from your google drive. It says "quota exceeded". Seems like there are some restrictions from your side. Could you resolve it?

Hi, I tried the download link just now, and it seems normal. Is there anything wrong with your internet? Besides, how about the download link in [Trackit](https://github.com/researchmm/TracKit).
