### ISSUE TITLE
Permission on LaSOT Please

### ISSUE THREAD

**Issue by kasuo511** [researchmm/SiamDW#94]
Hi,
Failed to download LaSOT dataset，hope you can release the permission, thanks a lot!
![permission](https://user-images.githubusercontent.com/19659016/86081934-36466f80-bac9-11ea-8f7e-514bfefc98bd.png)

**Comment by JudasDie** [comment]
> Hi,
> Failed to download LaSOT dataset，hope you can release the permission, thanks a lot!
> ![permission](https://user-images.githubusercontent.com/19659016/86081934-36466f80-bac9-11ea-8f7e-514bfefc98bd.png)
Hi, I have fixed it. Please try that again.

**Comment by kasuo511** [comment]
> > Hi,
> > Failed to download LaSOT dataset，hope you can release the permission, thanks a lot!
> > ![permission](https://user-images.githubusercontent.com/19659016/86081934-36466f80-bac9-11ea-8f7e-514bfefc98bd.png)
> > Hi, I have fixed it. Please try that again.

Unfortunately, the request was still rejected, just as it was

**Comment by JudasDie** [comment]
> > > Hi,
> > > Failed to download LaSOT dataset，hope you can release the permission, thanks a lot!
> > > ![permission](https://user-images.githubusercontent.com/19659016/86081934-36466f80-bac9-11ea-8f7e-514bfefc98bd.png)
> > > Hi, I have fixed it. Please try that again.
> 
> Unfortunately, the request was still rejected, just as it was

How about this [link](https://drive.google.com/file/d/1wb6KnGfmLLWkfPgR6kzZe6RxvEGyKujH/view?usp=sharing).
